"""Emit the Hero Talent Compass seed migration.

    python tools/talent_emit.py > supabase/migrations/027_talent_seed.sql

Idempotent: safe to re-run after editing wording — it replaces version 'v1'
content wholesale, so nothing drifts out of sync.
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from talent_seed import (SECTIONS, ITEMS, CHOICE, C_SCALE, AGREE,  # noqa: E402
                         DEMOTIVATORS_1, DEMOTIVATORS_2, REFLECT)
from talent_scenarios import SCEN, E6_NOTE  # noqa: E402

def q(v):
    return "'" + str(v).replace("'", "''") + "'"

def j(d):
    return q(json.dumps(d, ensure_ascii=False)) + "::jsonb"

out = []
w = out.append

w("-- 027_talent_seed.sql — GENERATED by tools/talent_emit.py. Do not hand-edit.")
w("-- Question bank v1: 47 items in en / ms-MY / id-ID.")
w("-- Re-running replaces v1 content in place; attempts and responses are untouched.")
w("begin;")
w("")
w("insert into talent_versions (code, name) values ('v1', 'Hero Talent Compass v1')")
w("  on conflict (code) do nothing;")
w("")
w("-- wipe v1 content only (responses reference questions, so clear those first if reseeding)")
w("delete from talent_options where question_id in (")
w("  select q.id from talent_questions q join talent_sections s on s.id = q.section_id")
w("  where s.version_id = (select id from talent_versions where code='v1'));")
w("delete from talent_questions where section_id in (")
w("  select id from talent_sections where version_id = (select id from talent_versions where code='v1'));")
w("delete from talent_sections where version_id = (select id from talent_versions where code='v1');")
w("")

for i, (code, title, intro) in enumerate(SECTIONS):
    w(f"insert into talent_sections (version_id, code, title, intro, sort_order) values "
      f"((select id from talent_versions where code='v1'), {q(code)}, {j(title)}, {j(intro)}, {i});")
w("")

SEC = "(select s.id from talent_sections s join talent_versions v on v.id=s.version_id where v.code='v1' and s.code=%s)"

def add_question(sec, code, kind, stem, dim, reverse, order, helper=None,
                 randomise=False, required=True, max_len=None):
    w(f"insert into talent_questions (section_id, code, kind, stem, helper, dimension, "
      f"reverse_scored, randomise_options, required, max_length, sort_order) values ("
      f"{SEC % q(sec)}, {q(code)}, {q(kind)}, {j(stem)}, "
      f"{j(helper) if helper else 'null'}, {q(dim) if dim else 'null'}, "
      f"{'true' if reverse else 'false'}, {'true' if randomise else 'false'}, "
      f"{'true' if required else 'false'}, {max_len or 'null'}, {order});")

QID = ("(select q.id from talent_questions q join talent_sections s on s.id=q.section_id "
       "join talent_versions v on v.id=s.version_id where v.code='v1' and q.code=%s)")

def add_option(qcode, value, label, contributes, order):
    w(f"insert into talent_options (question_id, value, label, contributes, sort_order) values ("
      f"{QID % q(qcode)}, {value}, {j(label)}, {j(contributes)}, {order});")

# ---- A, B, D scale/frequency items -------------------------------------
order = 0
for sec, code, kind, stem, scale, contrib, reverse in ITEMS:
    dim = next(iter(contrib))
    add_question(sec, code, kind, stem, dim, reverse, order)
    for idx, (val, label) in enumerate(scale):
        # a 5-point answer contributes (value-3)/2 * weight, so 3 is neutral and
        # a reverse-scored item flips the sign — one rule, no special cases.
        factor = (val - 3) / 2.0
        if reverse:
            factor = -factor
        add_option(code, val, label, {k: round(v * factor, 3) + 0.0 for k, v in contrib.items()}, idx)
    order += 1
w("")

# ---- C forced-choice ----------------------------------------------------
for n, (code, stem, opts) in enumerate(CHOICE):
    add_question("C", code, "choice", stem, "motivation", False, n, randomise=True)
    for idx, (val, label, contrib) in enumerate(opts):
        add_option(code, val, label, contrib, idx)

for n, (code, stem, contrib) in enumerate(C_SCALE):
    add_question("C", code, "scale5", stem, next(iter(contrib)), False, 10 + n)
    for idx, (val, label) in enumerate(AGREE):
        factor = (val - 3) / 2.0
        add_option(code, val, label, {k: round(v * factor, 3) + 0.0 for k, v in contrib.items()}, idx)

# demotivators: multi-select, each option is independent
for n, (code, bank) in enumerate((("C7", DEMOTIVATORS_1), ("C8", DEMOTIVATORS_2))):
    stem = {
        "en": "Which of these drains your motivation most? Choose up to three.",
        "ms-MY": "Antara berikut, yang mana paling melemahkan motivasi anda? Pilih sehingga tiga.",
        "id-ID": "Mana yang paling menurunkan motivasi Anda? Pilih maksimal tiga.",
    }
    add_question("C", code, "choice", stem, "demotivator", False, 20 + n, required=False)
    for idx, (key, label) in enumerate(bank):
        add_option(code, idx + 1, label, {f"demotivator.{key}": 1}, idx)
w("")

# ---- E scenarios --------------------------------------------------------
for n, (code, stem, opts) in enumerate(SCEN):
    helper = E6_NOTE if code == "E6" else None
    add_question("E", code, "scenario", stem, "role", False, n, helper=helper, randomise=True)
    for idx, (val, label, contrib) in enumerate(opts):
        add_option(code, val, label, contrib, idx)
w("")

# ---- F written ----------------------------------------------------------
for n, (code, stem) in enumerate(REFLECT):
    add_question("F", code, "text", stem, "reflection", False, n, required=False, max_len=1500)
w("")

# ---- seed the AG Leadership event ---------------------------------------
w("insert into talent_events (code, name, version_id, country_scope, languages, status, "
  "max_participants, timezone) values ('AGLEADERSHIP', 'AG Leadership Programme', "
  "(select id from talent_versions where code='v1'), 'MIXED', "
  "array['en','ms-MY','id-ID'], 'active', 200, 'Asia/Kuala_Lumpur')")
w("  on conflict do nothing;")
w("")
w("commit;")
w("")
w("select 'sections' as check, count(*)::text from talent_sections union all")
w("select 'questions', count(*)::text from talent_questions union all")
w("select 'options', count(*)::text from talent_options union all")
w("select 'events', count(*)::text from talent_events;")

print("\n".join(out))
