-- ============================================================
-- 004_curriculum_v1.sql — Seed Curriculum v1, Days 2–30 (spec §10)
-- DB-driven, editable by Admin. Trilingual en / ms-MY / id-ID.
-- Phases: 1 Foundation(1-5) · 2 Prospecting(6-12) · 3 Presentation(13-21) · 4 Closing(22-30)
-- ============================================================

insert into curriculum_days (version_id, day_no, phase, title, objective, content, required_action, evidence_requirement, reflection_question, xp_amount, needs_review)
select v.id, x.day_no, x.phase,
  x.title::jsonb, x.objective::jsonb, x.content::jsonb,
  x.required_action::jsonb, x.evidence::jsonb, x.reflection::jsonb,
  x.xp, true
from curriculum_versions v
cross join (values
-- ===== PHASE 1 (2-5) =====
(2,1,
 '{"en":"Professional Identity & Character","ms-MY":"Identiti Profesional & Sahsiah","id-ID":"Identitas Profesional & Karakter"}',
 '{"en":"Define who you are as a professional; strengths, gaps, conduct.","ms-MY":"Tentukan identiti profesional anda; kekuatan, kelemahan, tatakelakuan.","id-ID":"Tetapkan identitas profesional Anda; kekuatan, kelemahan, etika."}',
 '{"en":"Character comes before commission. Your name is your brand — protect it with integrity in every interaction.","ms-MY":"Sahsiah sebelum komisen. Nama anda ialah jenama anda — jaga dengan integriti.","id-ID":"Karakter sebelum komisi. Nama Anda adalah merek Anda — jaga dengan integritas."}',
 '{"en":"Complete your professional profile and write a character reflection.","ms-MY":"Lengkapkan profil profesional dan tulis refleksi sahsiah.","id-ID":"Lengkapi profil profesional dan tulis refleksi karakter."}',
 '{"en":"Completed profile + character reflection + improvement commitment","ms-MY":"Profil lengkap + refleksi sahsiah + komitmen penambahbaikan","id-ID":"Profil lengkap + refleksi karakter + komitmen perbaikan"}',
 '{"en":"Which strength will you use most, and which gap will you fix first?","ms-MY":"Kekuatan mana anda guna paling banyak, kelemahan mana anda baiki dulu?","id-ID":"Kekuatan mana yang paling Anda pakai, kelemahan mana yang diperbaiki dulu?"}',
 10),
(3,1,
 '{"en":"System & Work Setup","ms-MY":"Persediaan Sistem & Kerja","id-ID":"Penyiapan Sistem & Kerja"}',
 '{"en":"Complete approved account, social, project and work-system setup.","ms-MY":"Lengkapkan persediaan akaun, sosial, projek dan sistem kerja.","id-ID":"Selesaikan penyiapan akun, sosial, proyek dan sistem kerja."}',
 '{"en":"A warrior with sharp tools moves fast. Confirm access to every approved tool today. Never share passwords.","ms-MY":"Warrior dengan alat lengkap bergerak pantas. Sahkan akses semua alat hari ini. Jangan kongsi kata laluan.","id-ID":"Warrior dengan alat lengkap bergerak cepat. Pastikan akses semua alat hari ini. Jangan bagikan kata sandi."}',
 '{"en":"Finish the setup checklist and confirm tool access.","ms-MY":"Siapkan senarai semak persediaan dan sahkan akses alat.","id-ID":"Selesaikan checklist penyiapan dan konfirmasi akses alat."}',
 '{"en":"Readiness checklist + approved confirmation (no passwords/secrets)","ms-MY":"Senarai semak + pengesahan (tanpa kata laluan/rahsia)","id-ID":"Checklist + konfirmasi (tanpa kata sandi/rahasia)"}',
 '{"en":"Which tool will save you the most time daily?","ms-MY":"Alat mana paling menjimatkan masa anda setiap hari?","id-ID":"Alat mana yang paling menghemat waktu Anda setiap hari?"}',
 10),
(4,1,
 '{"en":"Market, Customer & Project Focus","ms-MY":"Fokus Pasaran, Pelanggan & Projek","id-ID":"Fokus Pasar, Pelanggan & Proyek"}',
 '{"en":"Choose an approved market/project focus and define your customer.","ms-MY":"Pilih fokus pasaran/projek yang diluluskan dan kenal pasti pelanggan.","id-ID":"Pilih fokus pasar/proyek yang disetujui dan kenali pelanggan Anda."}',
 '{"en":"Focus beats spray-and-pray. One market, one customer profile, one approved value story — mastered.","ms-MY":"Fokus mengalahkan bedil rambang. Satu pasaran, satu profil pelanggan, satu cerita nilai.","id-ID":"Fokus mengalahkan asal tembak. Satu pasar, satu profil pelanggan, satu cerita nilai."}',
 '{"en":"Select your focus, write the customer profile, finish the approved project learning.","ms-MY":"Pilih fokus, tulis profil pelanggan, habiskan pembelajaran projek.","id-ID":"Pilih fokus, tulis profil pelanggan, selesaikan pembelajaran proyek."}',
 '{"en":"Selected focus + customer profile + project-learning completion","ms-MY":"Fokus + profil pelanggan + pembelajaran projek selesai","id-ID":"Fokus + profil pelanggan + pembelajaran proyek selesai"}',
 '{"en":"Why does this customer need this project?","ms-MY":"Mengapa pelanggan ini perlukan projek ini?","id-ID":"Mengapa pelanggan ini membutuhkan proyek ini?"}',
 10),
(5,1,
 '{"en":"Build the First Lead List","ms-MY":"Bina Senarai Lead Pertama","id-ID":"Bangun Daftar Lead Pertama"}',
 '{"en":"Prepare an initial contact list and an ethical outreach plan.","ms-MY":"Sediakan senarai kenalan awal dan pelan hubungan beretika.","id-ID":"Siapkan daftar kontak awal dan rencana pendekatan yang etis."}',
 '{"en":"Your network is your first pipeline. List contacts respectfully — no unnecessary personal information.","ms-MY":"Rangkaian anda ialah pipeline pertama. Senaraikan kenalan dengan hormat.","id-ID":"Jaringan Anda adalah pipeline pertama. Daftarkan kontak dengan hormat."}',
 '{"en":"Create your first lead records and plan the first actions.","ms-MY":"Cipta rekod lead pertama dan rancang tindakan pertama.","id-ID":"Buat catatan lead pertama dan rencanakan aksi pertama."}',
 '{"en":"Lead records created + planned first actions","ms-MY":"Rekod lead dicipta + tindakan pertama dirancang","id-ID":"Catatan lead dibuat + aksi pertama direncanakan"}',
 '{"en":"Who are your 5 warmest contacts and why?","ms-MY":"Siapa 5 kenalan paling hangat anda dan mengapa?","id-ID":"Siapa 5 kontak terhangat Anda dan mengapa?"}',
 15),
-- ===== PHASE 2 (6-12) =====
(6,2,
 '{"en":"Cold, Warm & Hot Leads","ms-MY":"Lead Sejuk, Suam & Panas","id-ID":"Lead Dingin, Hangat & Panas"}',
 '{"en":"Understand lead categories; match communication to the stage.","ms-MY":"Fahami kategori lead; padankan komunikasi dengan tahap.","id-ID":"Pahami kategori lead; sesuaikan komunikasi dengan tahap."}',
 '{"en":"Hook, Trust, then Closing or next action — each lead stage needs a different first move.","ms-MY":"Hook, Trust, kemudian Closing — setiap tahap perlukan langkah berbeza.","id-ID":"Hook, Trust, lalu Closing — setiap tahap butuh langkah berbeda."}',
 '{"en":"Classify a sample of your leads and explain each classification.","ms-MY":"Kelaskan sampel lead anda dan jelaskan setiap kelas.","id-ID":"Klasifikasikan sampel lead Anda dan jelaskan alasannya."}',
 '{"en":"Classified lead sample + explanation","ms-MY":"Sampel lead berkelas + penjelasan","id-ID":"Sampel lead terklasifikasi + penjelasan"}',
 '{"en":"What makes a lead move from warm to hot?","ms-MY":"Apa yang menjadikan lead suam menjadi panas?","id-ID":"Apa yang membuat lead hangat menjadi panas?"}',
 10),
(7,2,
 '{"en":"Daily Prospecting Rhythm","ms-MY":"Rentak Prospek Harian","id-ID":"Ritme Prospek Harian"}',
 '{"en":"Build a consistent daily outreach habit with an achievable target.","ms-MY":"Bina tabiat hubungan harian yang konsisten dengan sasaran boleh capai.","id-ID":"Bangun kebiasaan pendekatan harian dengan target yang realistis."}',
 '{"en":"Consistency beats intensity. Small daily numbers, honoured every day, build an unstoppable pipeline.","ms-MY":"Konsistensi mengalahkan intensiti. Angka kecil setiap hari membina pipeline kukuh.","id-ID":"Konsistensi mengalahkan intensitas. Angka kecil setiap hari membangun pipeline kuat."}',
 '{"en":"Write your daily prospecting plan and complete today''s outreach.","ms-MY":"Tulis pelan prospek harian dan siapkan hubungan hari ini.","id-ID":"Tulis rencana prospek harian dan selesaikan pendekatan hari ini."}',
 '{"en":"Daily prospecting plan + completed activity records","ms-MY":"Pelan prospek + rekod aktiviti selesai","id-ID":"Rencana prospek + catatan aktivitas selesai"}',
 '{"en":"What daily number can you honour even on your busiest day?","ms-MY":"Angka harian apa yang anda mampu tunaikan walau sibuk?","id-ID":"Angka harian apa yang bisa Anda penuhi bahkan saat tersibuk?"}',
 10),
(8,2,
 '{"en":"First Message & Hook","ms-MY":"Mesej Pertama & Hook","id-ID":"Pesan Pertama & Hook"}',
 '{"en":"Create approved introductions focused on relevance and value.","ms-MY":"Cipta mesej pengenalan yang relevan dan bernilai.","id-ID":"Buat pesan perkenalan yang relevan dan bernilai."}',
 '{"en":"No spam, no misleading claims. A great hook speaks to THEIR situation, not your sale.","ms-MY":"Tiada spam, tiada dakwaan mengelirukan. Hook hebat bercakap tentang situasi MEREKA.","id-ID":"Tanpa spam, tanpa klaim menyesatkan. Hook hebat bicara tentang situasi MEREKA."}',
 '{"en":"Draft message examples and send today''s outreach.","ms-MY":"Draf contoh mesej dan hantar hubungan hari ini.","id-ID":"Draf contoh pesan dan kirim pendekatan hari ini."}',
 '{"en":"Draft + approved message examples + outreach activity","ms-MY":"Draf + contoh mesej + aktiviti hubungan","id-ID":"Draf + contoh pesan + aktivitas pendekatan"}',
 '{"en":"Which hook earned a reply today, and why?","ms-MY":"Hook mana mendapat balasan hari ini, mengapa?","id-ID":"Hook mana yang dibalas hari ini, mengapa?"}',
 10),
(9,2,
 '{"en":"Needs Discovery","ms-MY":"Penerokaan Keperluan","id-ID":"Penggalian Kebutuhan"}',
 '{"en":"Ask the right questions; understand needs, timing and constraints.","ms-MY":"Tanya soalan tepat; fahami keperluan, masa dan kekangan.","id-ID":"Ajukan pertanyaan tepat; pahami kebutuhan, waktu dan kendala."}',
 '{"en":"Never push an unsuitable solution. Discovery protects the customer AND your reputation.","ms-MY":"Jangan tolak penyelesaian tak sesuai. Penerokaan melindungi pelanggan DAN reputasi anda.","id-ID":"Jangan paksakan solusi yang tak cocok. Penggalian melindungi pelanggan DAN reputasi Anda."}',
 '{"en":"Use the discovery-question checklist on a real conversation and record lead notes.","ms-MY":"Guna senarai soalan penerokaan dalam perbualan sebenar dan catat nota lead.","id-ID":"Gunakan checklist pertanyaan penggalian dalam percakapan nyata dan catat notanya."}',
 '{"en":"Discovery-question checklist + lead notes","ms-MY":"Senarai soalan penerokaan + nota lead","id-ID":"Checklist pertanyaan penggalian + catatan lead"}',
 '{"en":"What surprised you about your customer''s real need?","ms-MY":"Apa yang mengejutkan tentang keperluan sebenar pelanggan?","id-ID":"Apa yang mengejutkan dari kebutuhan asli pelanggan Anda?"}',
 10),
(10,2,
 '{"en":"Building Trust","ms-MY":"Membina Kepercayaan","id-ID":"Membangun Kepercayaan"}',
 '{"en":"Improve credibility; provide useful information the approved way.","ms-MY":"Tingkatkan kredibiliti; beri maklumat berguna dengan cara diluluskan.","id-ID":"Tingkatkan kredibilitas; beri informasi berguna dengan cara yang disetujui."}',
 '{"en":"Trust is the currency of AG. Give value before you ask for anything.","ms-MY":"Kepercayaan ialah mata wang AG. Beri nilai sebelum meminta apa-apa.","id-ID":"Kepercayaan adalah mata uang AG. Beri nilai sebelum meminta apa pun."}',
 '{"en":"Send one genuinely helpful follow-up and reflect on it.","ms-MY":"Hantar satu susulan yang benar-benar membantu dan buat refleksi.","id-ID":"Kirim satu follow-up yang benar-benar membantu dan refleksikan."}',
 '{"en":"Follow-up example + trust-building reflection","ms-MY":"Contoh susulan + refleksi kepercayaan","id-ID":"Contoh follow-up + refleksi kepercayaan"}',
 '{"en":"What did you GIVE today before asking?","ms-MY":"Apa yang anda BERI hari ini sebelum meminta?","id-ID":"Apa yang Anda BERI hari ini sebelum meminta?"}',
 10),
(11,2,
 '{"en":"Follow-Up Discipline","ms-MY":"Disiplin Susulan","id-ID":"Disiplin Follow-Up"}',
 '{"en":"Create a controlled follow-up schedule — helpful, never excessive.","ms-MY":"Bina jadual susulan terkawal — membantu, bukan mengganggu.","id-ID":"Buat jadwal follow-up terkontrol — membantu, bukan mengganggu."}',
 '{"en":"Fortune is in the follow-up. The line between persistence and pestering is respect for the customer''s time.","ms-MY":"Rezeki dalam susulan. Beza gigih dan mengganggu ialah hormat pada masa pelanggan.","id-ID":"Rezeki ada di follow-up. Beda gigih dan mengganggu adalah hormat pada waktu pelanggan."}',
 '{"en":"Create follow-up tasks for every open lead and update activity.","ms-MY":"Cipta tugasan susulan untuk setiap lead terbuka dan kemas kini aktiviti.","id-ID":"Buat tugas follow-up untuk setiap lead terbuka dan perbarui aktivitas."}',
 '{"en":"Follow-up tasks created + updated lead activity","ms-MY":"Tugasan susulan dicipta + aktiviti lead dikemas kini","id-ID":"Tugas follow-up dibuat + aktivitas lead diperbarui"}',
 '{"en":"Which lead have you been avoiding, and what will you do?","ms-MY":"Lead mana anda elakkan, apa tindakan anda?","id-ID":"Lead mana yang Anda hindari, apa tindakan Anda?"}',
 10),
(12,2,
 '{"en":"Appointment Setting","ms-MY":"Menetapkan Temu Janji","id-ID":"Mengatur Janji Temu"}',
 '{"en":"Move qualified engagement toward a clear next action.","ms-MY":"Gerakkan lead layak ke tindakan seterusnya yang jelas.","id-ID":"Gerakkan lead berkualitas menuju aksi berikutnya yang jelas."}',
 '{"en":"Every good conversation deserves a next step: a call, meeting, presentation or viewing. Ask for it clearly.","ms-MY":"Setiap perbualan baik layak langkah seterusnya: panggilan, temu janji atau lawatan.","id-ID":"Setiap percakapan baik layak langkah berikutnya: telepon, pertemuan atau kunjungan."}',
 '{"en":"Book one appointment (or complete an approved practice) with preparation notes.","ms-MY":"Tempah satu temu janji (atau latihan diluluskan) dengan nota persediaan.","id-ID":"Buat satu janji temu (atau latihan yang disetujui) dengan catatan persiapan."}',
 '{"en":"Appointment record (or simulated practice) + preparation notes","ms-MY":"Rekod temu janji (atau simulasi) + nota persediaan","id-ID":"Catatan janji temu (atau simulasi) + catatan persiapan"}',
 '{"en":"What words did you use to ask for the appointment?","ms-MY":"Ayat apa anda guna untuk minta temu janji?","id-ID":"Kalimat apa yang Anda pakai untuk meminta janji temu?"}',
 15),
-- ===== PHASE 3 (13-21) =====
(13,3,
 '{"en":"Project & Product Mastery","ms-MY":"Penguasaan Projek & Produk","id-ID":"Penguasaan Proyek & Produk"}',
 '{"en":"Study approved project info; know what may and may not be claimed.","ms-MY":"Pelajari maklumat projek; tahu apa boleh dan tak boleh didakwa.","id-ID":"Pelajari info proyek; tahu apa yang boleh dan tidak boleh diklaim."}',
 '{"en":"Mastery creates confidence; honesty creates trust. Only claim what the approved materials support.","ms-MY":"Penguasaan bina keyakinan; kejujuran bina kepercayaan. Dakwa hanya yang disokong bahan rasmi.","id-ID":"Penguasaan membangun percaya diri; kejujuran membangun kepercayaan."}',
 '{"en":"Pass the knowledge check and write an approved project summary.","ms-MY":"Lulus semakan pengetahuan dan tulis ringkasan projek.","id-ID":"Lulus uji pengetahuan dan tulis ringkasan proyek."}',
 '{"en":"Knowledge check + approved project summary","ms-MY":"Semakan pengetahuan + ringkasan projek","id-ID":"Uji pengetahuan + ringkasan proyek"}',
 '{"en":"Which project fact will customers care about most?","ms-MY":"Fakta projek mana paling penting bagi pelanggan?","id-ID":"Fakta proyek mana yang paling penting bagi pelanggan?"}',
 10),
(14,3,
 '{"en":"Value Proposition","ms-MY":"Cadangan Nilai","id-ID":"Proposisi Nilai"}',
 '{"en":"Connect features to customer needs; benefits without exaggeration.","ms-MY":"Kaitkan ciri dengan keperluan; manfaat tanpa dibesar-besarkan.","id-ID":"Hubungkan fitur dengan kebutuhan; manfaat tanpa berlebihan."}',
 '{"en":"Features tell, benefits sell, truth keeps. Match every feature to a real customer need.","ms-MY":"Ciri memberitahu, manfaat menjual, kebenaran mengekal.","id-ID":"Fitur memberi tahu, manfaat menjual, kebenaran mempertahankan."}',
 '{"en":"Write a customer-specific value statement.","ms-MY":"Tulis kenyataan nilai khusus pelanggan.","id-ID":"Tulis pernyataan nilai khusus pelanggan."}',
 '{"en":"Customer-specific value statement (Coach review)","ms-MY":"Kenyataan nilai khusus pelanggan (semakan Coach)","id-ID":"Pernyataan nilai khusus pelanggan (tinjauan Coach)"}',
 '{"en":"Complete: this project helps [customer] achieve [outcome] because…","ms-MY":"Lengkapkan: projek ini membantu [pelanggan] capai [hasil] kerana…","id-ID":"Lengkapi: proyek ini membantu [pelanggan] mencapai [hasil] karena…"}',
 10),
(15,3,
 '{"en":"Presentation Structure","ms-MY":"Struktur Pembentangan","id-ID":"Struktur Presentasi"}',
 '{"en":"Prepare a clear presentation: opening, discovery, recommendation, next action.","ms-MY":"Sedia pembentangan jelas: pembukaan, penerokaan, cadangan, tindakan.","id-ID":"Siapkan presentasi jelas: pembukaan, penggalian, rekomendasi, aksi."}',
 '{"en":"A structured presentation respects the customer''s time and guides a confident decision.","ms-MY":"Pembentangan berstruktur menghormati masa pelanggan.","id-ID":"Presentasi terstruktur menghormati waktu pelanggan."}',
 '{"en":"Build your presentation outline and practise it once.","ms-MY":"Bina rangka pembentangan dan berlatih sekali.","id-ID":"Buat kerangka presentasi dan latih sekali."}',
 '{"en":"Presentation outline + practice recording or approved observation","ms-MY":"Rangka pembentangan + rakaman latihan","id-ID":"Kerangka presentasi + rekaman latihan"}',
 '{"en":"Which part of your presentation feels weakest?","ms-MY":"Bahagian mana pembentangan anda paling lemah?","id-ID":"Bagian mana presentasi Anda yang paling lemah?"}',
 10),
(16,3,
 '{"en":"Country-Specific Customer Process","ms-MY":"Proses Pelanggan Ikut Negara","id-ID":"Proses Pelanggan Spesifik Negara"}',
 '{"en":"Learn the approved customer journey for your country and escalation routes.","ms-MY":"Pelajari perjalanan pelanggan diluluskan untuk negara anda.","id-ID":"Pelajari perjalanan pelanggan yang disetujui untuk negara Anda."}',
 '{"en":"Follow the approved process only. When unsure, escalate — never guess on legal or financing matters.","ms-MY":"Ikut proses diluluskan sahaja. Jika ragu, rujuk atasan — jangan agak hal undang-undang.","id-ID":"Ikuti proses yang disetujui. Jika ragu, eskalasi — jangan menebak soal legal."}',
 '{"en":"Complete the country-specific checklist and confirm your knowledge.","ms-MY":"Siapkan senarai semak negara dan sahkan pengetahuan.","id-ID":"Selesaikan checklist negara dan konfirmasi pengetahuan."}',
 '{"en":"Country-specific checklist + knowledge confirmation","ms-MY":"Senarai semak negara + pengesahan pengetahuan","id-ID":"Checklist negara + konfirmasi pengetahuan"}',
 '{"en":"What is the correct escalation route when a customer asks beyond your authority?","ms-MY":"Apa laluan rujukan betul bila pelanggan tanya di luar bidang kuasa?","id-ID":"Apa jalur eskalasi yang benar saat pelanggan bertanya di luar wewenang?"}',
 10),
(17,3,
 '{"en":"Viewing / Presentation Preparation","ms-MY":"Persediaan Lawatan / Pembentangan","id-ID":"Persiapan Kunjungan / Presentasi"}',
 '{"en":"Prepare customer info, confirm the appointment, prepare materials.","ms-MY":"Sedia maklumat pelanggan, sahkan temu janji, sedia bahan.","id-ID":"Siapkan info pelanggan, konfirmasi janji, siapkan materi."}',
 '{"en":"Preparation is respect. Know the customer, the property and your desired next action before arriving.","ms-MY":"Persediaan itu hormat. Kenali pelanggan, hartanah dan tindakan seterusnya.","id-ID":"Persiapan adalah rasa hormat. Kenali pelanggan, properti dan aksi berikutnya."}',
 '{"en":"Write a full viewing or presentation plan.","ms-MY":"Tulis pelan lawatan atau pembentangan penuh.","id-ID":"Tulis rencana kunjungan atau presentasi lengkap."}',
 '{"en":"Viewing or presentation plan","ms-MY":"Pelan lawatan atau pembentangan","id-ID":"Rencana kunjungan atau presentasi"}',
 '{"en":"What next action will you ask for at the end?","ms-MY":"Tindakan apa anda minta di akhir sesi?","id-ID":"Aksi apa yang akan Anda minta di akhir sesi?"}',
 10),
(18,3,
 '{"en":"Conducting the Viewing / Presentation","ms-MY":"Menjalankan Lawatan / Pembentangan","id-ID":"Melakukan Kunjungan / Presentasi"}',
 '{"en":"Deliver the approved experience; listen; capture concerns.","ms-MY":"Sampaikan pengalaman diluluskan; dengar; catat kebimbangan.","id-ID":"Berikan pengalaman yang disetujui; dengarkan; catat kekhawatiran."}',
 '{"en":"Listen more than you speak. Capture every question — objections are directions, not rejections.","ms-MY":"Dengar lebih dari bercakap. Bantahan ialah arah, bukan penolakan.","id-ID":"Dengarkan lebih banyak daripada bicara. Keberatan adalah arah, bukan penolakan."}',
 '{"en":"Conduct the session and record the outcome and questions.","ms-MY":"Jalankan sesi dan rekod hasil serta soalan.","id-ID":"Lakukan sesi dan catat hasil serta pertanyaan."}',
 '{"en":"Session record + customer questions + next-step status","ms-MY":"Rekod sesi + soalan pelanggan + status langkah seterusnya","id-ID":"Catatan sesi + pertanyaan pelanggan + status langkah berikutnya"}',
 '{"en":"What concern did you hear that you did not expect?","ms-MY":"Kebimbangan apa yang anda tak jangka?","id-ID":"Kekhawatiran apa yang tidak Anda duga?"}',
 15),
(19,3,
 '{"en":"Post-Viewing Follow-Up","ms-MY":"Susulan Selepas Lawatan","id-ID":"Follow-Up Pasca Kunjungan"}',
 '{"en":"Answer questions, record objections, agree on the next action.","ms-MY":"Jawab soalan, rekod bantahan, sepakati tindakan seterusnya.","id-ID":"Jawab pertanyaan, catat keberatan, sepakati aksi berikutnya."}',
 '{"en":"The 24 hours after a viewing decide the deal. Respond fast, honestly and with the next step ready.","ms-MY":"24 jam selepas lawatan menentukan urusan. Balas pantas dan jujur.","id-ID":"24 jam setelah kunjungan menentukan transaksi. Balas cepat dan jujur."}',
 '{"en":"Complete the follow-up and update the pipeline status.","ms-MY":"Siapkan susulan dan kemas kini status pipeline.","id-ID":"Selesaikan follow-up dan perbarui status pipeline."}',
 '{"en":"Follow-up record + updated pipeline status","ms-MY":"Rekod susulan + status pipeline dikemas kini","id-ID":"Catatan follow-up + status pipeline diperbarui"}',
 '{"en":"What is this customer''s real remaining question?","ms-MY":"Apa soalan sebenar yang tinggal pada pelanggan ini?","id-ID":"Apa pertanyaan sebenarnya yang tersisa dari pelanggan ini?"}',
 10),
(20,3,
 '{"en":"Objection Handling","ms-MY":"Menangani Bantahan","id-ID":"Menangani Keberatan"}',
 '{"en":"Distinguish question, concern, timing and mismatch; respond honestly.","ms-MY":"Bezakan soalan, kebimbangan, masa dan ketidaksesuaian; jawab jujur.","id-ID":"Bedakan pertanyaan, kekhawatiran, waktu dan ketidakcocokan; jawab jujur."}',
 '{"en":"An objection understood is half-answered. If the product truly does not fit — say so, and keep the trust.","ms-MY":"Bantahan yang difahami separuh terjawab. Jika benar tak sesuai — katakan.","id-ID":"Keberatan yang dipahami sudah setengah terjawab. Jika memang tak cocok — katakan."}',
 '{"en":"Log today''s objections and write your response plan.","ms-MY":"Log bantahan hari ini dan tulis pelan jawapan.","id-ID":"Catat keberatan hari ini dan tulis rencana respons."}',
 '{"en":"Objection log + response plan (Coach feedback)","ms-MY":"Log bantahan + pelan jawapan (maklum balas Coach)","id-ID":"Catatan keberatan + rencana respons (umpan balik Coach)"}',
 '{"en":"Which objection is really a timing issue in disguise?","ms-MY":"Bantahan mana sebenarnya isu masa?","id-ID":"Keberatan mana yang sebenarnya masalah waktu?"}',
 10),
(21,3,
 '{"en":"Negotiation & Decision Support","ms-MY":"Rundingan & Sokongan Keputusan","id-ID":"Negosiasi & Dukungan Keputusan"}',
 '{"en":"Support a responsible decision using approved information only.","ms-MY":"Sokong keputusan bertanggungjawab guna maklumat diluluskan sahaja.","id-ID":"Dukung keputusan bertanggung jawab dengan informasi yang disetujui."}',
 '{"en":"No pressure, no unauthorised promises. Your job is to help the customer decide well — even if slowly.","ms-MY":"Tiada tekanan, tiada janji tanpa kuasa. Bantu pelanggan buat keputusan baik.","id-ID":"Tanpa tekanan, tanpa janji tak sah. Bantu pelanggan memutuskan dengan baik."}',
 '{"en":"Record negotiation notes and the next-action plan.","ms-MY":"Rekod nota rundingan dan pelan tindakan seterusnya.","id-ID":"Catat nota negosiasi dan rencana aksi berikutnya."}',
 '{"en":"Negotiation notes + next-action plan","ms-MY":"Nota rundingan + pelan tindakan","id-ID":"Nota negosiasi + rencana aksi"}',
 '{"en":"Where did you almost over-promise today?","ms-MY":"Di mana anda hampir janji berlebihan hari ini?","id-ID":"Di mana Anda hampir berjanji berlebihan hari ini?"}',
 10),
-- ===== PHASE 4 (22-30) =====
(22,4,
 '{"en":"Closing Readiness","ms-MY":"Kesediaan Closing","id-ID":"Kesiapan Closing"}',
 '{"en":"Assess customer, documentation, internal support and next steps.","ms-MY":"Nilai pelanggan, dokumen, sokongan dalaman dan langkah seterusnya.","id-ID":"Nilai pelanggan, dokumen, dukungan internal dan langkah berikutnya."}',
 '{"en":"A closing fails on missing pieces. List every item, every owner, every date — before the customer says yes.","ms-MY":"Closing gagal kerana benda tertinggal. Senaraikan semua item dan pemilik.","id-ID":"Closing gagal karena hal terlewat. Daftarkan semua item dan pemiliknya."}',
 '{"en":"Complete the closing-readiness checklist for your strongest lead.","ms-MY":"Siapkan senarai semak kesediaan closing untuk lead terkuat.","id-ID":"Selesaikan checklist kesiapan closing untuk lead terkuat."}',
 '{"en":"Closing-readiness checklist + missing items and owner","ms-MY":"Senarai semak closing + item tertinggal dan pemilik","id-ID":"Checklist closing + item kurang dan pemiliknya"}',
 '{"en":"What single missing item most threatens this closing?","ms-MY":"Item tertinggal mana paling mengancam closing ini?","id-ID":"Item kurang mana yang paling mengancam closing ini?"}',
 10),
(23,4,
 '{"en":"Closing Is Helping","ms-MY":"Closing Itu Membantu","id-ID":"Closing Adalah Membantu"}',
 '{"en":"Reinforce that closing supports an appropriate customer decision.","ms-MY":"Tegaskan closing menyokong keputusan pelanggan yang wajar.","id-ID":"Tegaskan closing mendukung keputusan pelanggan yang tepat."}',
 '{"en":"When the fit is right, helping the customer decide IS the service. Hesitation can cost them the home they need.","ms-MY":"Bila sesuai, membantu pelanggan membuat keputusan ITULAH khidmat.","id-ID":"Saat cocok, membantu pelanggan memutuskan ITULAH pelayanan."}',
 '{"en":"Write your ethical closing reflection and a customer-value statement.","ms-MY":"Tulis refleksi closing beretika dan kenyataan nilai pelanggan.","id-ID":"Tulis refleksi closing etis dan pernyataan nilai pelanggan."}',
 '{"en":"Ethical closing reflection + customer-value statement","ms-MY":"Refleksi closing beretika + kenyataan nilai pelanggan","id-ID":"Refleksi closing etis + pernyataan nilai pelanggan"}',
 '{"en":"How does your strongest deal genuinely help that customer?","ms-MY":"Bagaimana urusan terkuat anda benar-benar membantu pelanggan itu?","id-ID":"Bagaimana transaksi terkuat Anda benar-benar membantu pelanggan itu?"}',
 10),
(24,4,
 '{"en":"Documentation & Approved Process","ms-MY":"Dokumentasi & Proses Diluluskan","id-ID":"Dokumentasi & Proses Resmi"}',
 '{"en":"Follow the approved country and company process; know the owners.","ms-MY":"Ikut proses negara dan syarikat; kenal pemilik proses.","id-ID":"Ikuti proses negara dan perusahaan; kenali pemilik proses."}',
 '{"en":"Paperwork done right protects everyone. Never expose protected documents unnecessarily.","ms-MY":"Dokumen betul melindungi semua. Jangan dedah dokumen terlindung.","id-ID":"Dokumen yang benar melindungi semua. Jangan buka dokumen terlindungi."}',
 '{"en":"Complete the process checklist for your active deal.","ms-MY":"Siapkan senarai semak proses untuk urusan aktif.","id-ID":"Selesaikan checklist proses untuk transaksi aktif."}',
 '{"en":"Process checklist (no protected documents exposed)","ms-MY":"Senarai semak proses (tanpa dokumen terlindung)","id-ID":"Checklist proses (tanpa dokumen terlindungi)"}',
 '{"en":"Which step of the process do you understand least?","ms-MY":"Langkah proses mana anda paling kurang faham?","id-ID":"Langkah proses mana yang paling kurang Anda pahami?"}',
 10),
(25,4,
 '{"en":"Pipeline Rescue","ms-MY":"Menyelamat Pipeline","id-ID":"Penyelamatan Pipeline"}',
 '{"en":"Review stalled leads: follow up, nurture, requalify or close responsibly.","ms-MY":"Semak lead tersekat: susul, bina, nilai semula atau tutup.","id-ID":"Tinjau lead macet: follow-up, rawat, kualifikasi ulang atau tutup."}',
 '{"en":"A stalled lead is a decision waiting for honesty. Rescue it, park it, or release it — never ignore it.","ms-MY":"Lead tersekat menunggu kejujuran. Selamatkan, simpan atau lepaskan.","id-ID":"Lead macet menunggu kejujuran. Selamatkan, simpan atau lepaskan."}',
 '{"en":"Review the pipeline and take action on selected leads.","ms-MY":"Semak pipeline dan bertindak ke atas lead terpilih.","id-ID":"Tinjau pipeline dan ambil tindakan pada lead terpilih."}',
 '{"en":"Pipeline review + actions for selected leads","ms-MY":"Semakan pipeline + tindakan lead terpilih","id-ID":"Tinjauan pipeline + tindakan lead terpilih"}',
 '{"en":"Which lead did you finally make an honest decision about?","ms-MY":"Lead mana anda akhirnya buat keputusan jujur?","id-ID":"Lead mana yang akhirnya Anda putuskan dengan jujur?"}',
 10),
(26,4,
 '{"en":"Personal Closing Plan","ms-MY":"Pelan Closing Peribadi","id-ID":"Rencana Closing Pribadi"}',
 '{"en":"Focused plan for the strongest opportunities: actions, owners, dates.","ms-MY":"Pelan fokus untuk peluang terkuat: tindakan, pemilik, tarikh.","id-ID":"Rencana fokus untuk peluang terkuat: aksi, pemilik, tanggal."}',
 '{"en":"Hope is not a plan. Name the deal, the blockers, the owner of each step and the date it happens.","ms-MY":"Harapan bukan pelan. Namakan urusan, halangan, pemilik dan tarikh.","id-ID":"Harapan bukan rencana. Sebutkan transaksi, hambatan, pemilik dan tanggal."}',
 '{"en":"Write your personal closing plan for Coach review.","ms-MY":"Tulis pelan closing peribadi untuk semakan Coach.","id-ID":"Tulis rencana closing pribadi untuk tinjauan Coach."}',
 '{"en":"Personal closing plan (Coach review)","ms-MY":"Pelan closing peribadi (semakan Coach)","id-ID":"Rencana closing pribadi (tinjauan Coach)"}',
 '{"en":"What happens in the next 72 hours on your best deal?","ms-MY":"Apa berlaku dalam 72 jam pada urusan terbaik anda?","id-ID":"Apa yang terjadi dalam 72 jam pada transaksi terbaik Anda?"}',
 15),
(27,4,
 '{"en":"Mentor Review","ms-MY":"Semakan Mentor","id-ID":"Tinjauan Mentor"}',
 '{"en":"Structured Coach review: progress, barriers, skills, next actions.","ms-MY":"Semakan Coach berstruktur: kemajuan, halangan, kemahiran.","id-ID":"Tinjauan Coach terstruktur: kemajuan, hambatan, keterampilan."}',
 '{"en":"Feedback is a gift from someone invested in your growth. Receive it openly, act on it quickly.","ms-MY":"Maklum balas ialah hadiah. Terima terbuka, bertindak pantas.","id-ID":"Umpan balik adalah hadiah. Terima dengan terbuka, tindak cepat."}',
 '{"en":"Complete the coaching session and acknowledge the report.","ms-MY":"Siapkan sesi coaching dan sahkan laporan.","id-ID":"Selesaikan sesi coaching dan akui laporannya."}',
 '{"en":"Coaching report + participant acknowledgement + action plan","ms-MY":"Laporan coaching + pengesahan + pelan tindakan","id-ID":"Laporan coaching + pengakuan + rencana aksi"}',
 '{"en":"Which coaching point stung — and why is it true?","ms-MY":"Teguran mana paling pedih — dan mengapa ia benar?","id-ID":"Masukan mana yang paling menusuk — dan mengapa itu benar?"}',
 20),
(28,4,
 '{"en":"Recruit & Educate Responsibly","ms-MY":"Rekrut & Didik Secara Bertanggungjawab","id-ID":"Rekrut & Didik dengan Bertanggung Jawab"}',
 '{"en":"An Elite Warrior grows by helping suitable people grow.","ms-MY":"Elite Warrior membesar dengan membantu orang sesuai membesar.","id-ID":"Elite Warrior bertumbuh dengan membantu orang yang tepat bertumbuh."}',
 '{"en":"Recruit people who fit, for their benefit — never spam, never pressure. Teaching others is the next level of mastery.","ms-MY":"Rekrut orang sesuai untuk manfaat mereka — bukan spam atau tekanan.","id-ID":"Rekrut orang yang cocok untuk kebaikan mereka — tanpa spam atau tekanan."}',
 '{"en":"Draft your recruitment or teaching plan.","ms-MY":"Draf pelan rekrutmen atau pengajaran anda.","id-ID":"Draf rencana rekrutmen atau pengajaran Anda."}',
 '{"en":"Recruitment or teaching plan (no spam recruiting)","ms-MY":"Pelan rekrutmen/pengajaran (tanpa spam)","id-ID":"Rencana rekrutmen/pengajaran (tanpa spam)"}',
 '{"en":"Who is ONE person who would genuinely thrive as a Warrior?","ms-MY":"Siapa SATU orang yang benar-benar sesuai jadi Warrior?","id-ID":"Siapa SATU orang yang benar-benar cocok menjadi Warrior?"}',
 10),
(29,4,
 '{"en":"My Hero Playbook","ms-MY":"Playbook Hero Saya","id-ID":"Playbook Hero Saya"}',
 '{"en":"Consolidate your personal operating system: routines, messages, follow-up, learning.","ms-MY":"Satukan sistem operasi peribadi: rutin, mesej, susulan.","id-ID":"Satukan sistem operasi pribadi: rutinitas, pesan, follow-up."}',
 '{"en":"What got you here, written down, becomes what keeps you growing. Document your winning routines.","ms-MY":"Apa yang bawa anda ke sini, bila ditulis, terus membesarkan anda.","id-ID":"Yang membawa Anda ke sini, bila ditulis, terus menumbuhkan Anda."}',
 '{"en":"Write your personal Hero playbook and continuation schedule.","ms-MY":"Tulis playbook Hero dan jadual kesinambungan.","id-ID":"Tulis playbook Hero dan jadwal keberlanjutan."}',
 '{"en":"Personal Hero playbook + continuation schedule","ms-MY":"Playbook Hero + jadual kesinambungan","id-ID":"Playbook Hero + jadwal keberlanjutan"}',
 '{"en":"Which routine from these 30 days will you never drop?","ms-MY":"Rutin mana dari 30 hari ini anda takkan tinggalkan?","id-ID":"Rutinitas mana dari 30 hari ini yang tak akan Anda tinggalkan?"}',
 15),
(30,4,
 '{"en":"Final Review & Next Journey","ms-MY":"Semakan Akhir & Perjalanan Seterusnya","id-ID":"Tinjauan Akhir & Perjalanan Berikutnya"}',
 '{"en":"Review verified activity, pipeline, character and learning; set the next stage.","ms-MY":"Semak aktiviti, pipeline, sahsiah dan pembelajaran; tetapkan tahap seterusnya.","id-ID":"Tinjau aktivitas, pipeline, karakter dan pembelajaran; tetapkan tahap berikutnya."}',
 '{"en":"Completing 30 days of verified action IS success — with or without a closing. The journey continues: post-closing growth, mentoring, leadership.","ms-MY":"Menamatkan 30 hari tindakan yang disahkan ITULAH kejayaan — dengan atau tanpa closing.","id-ID":"Menyelesaikan 30 hari aksi terverifikasi ADALAH keberhasilan — dengan atau tanpa closing."}',
 '{"en":"Submit your final reflection and continuation plan for Coach evaluation.","ms-MY":"Hantar refleksi akhir dan pelan kesinambungan untuk penilaian Coach.","id-ID":"Kirim refleksi akhir dan rencana lanjutan untuk evaluasi Coach."}',
 '{"en":"Final reflection + Coach evaluation + continuation plan + pathway","ms-MY":"Refleksi akhir + penilaian Coach + pelan kesinambungan","id-ID":"Refleksi akhir + evaluasi Coach + rencana lanjutan"}',
 '{"en":"Who are you now that you were not on Day 1?","ms-MY":"Siapa anda kini yang bukan anda pada Hari 1?","id-ID":"Siapa Anda sekarang yang bukan Anda di Hari 1?"}',
 30)
) as x(day_no, phase, title, objective, content, required_action, evidence, reflection, xp)
where v.version = 1
  and not exists (select 1 from curriculum_days cd where cd.version_id = v.id and cd.day_no = x.day_no);

-- verify
select count(*) as total_days from curriculum_days;
