-- ============================================================
-- 081_curriculum_country.sql — 30 DAYS v2, P2 (part 1): the country-content
-- architecture, and the integrity fix that makes it safe to use.
--
-- ADDITIVE. Content itself is created by 082 (generated by tools/curriculum_v2.py).
--
-- Audit §A7 found country_override was a hazard, not a feature:
--   unique (version_id, day_no, country_override)
-- treats NULLs as distinct, so it permitted unlimited duplicate GENERIC rows —
-- the exact row that most needed protecting — while the read paths had no
-- country filter and no deterministic tie-break. 079 fixed the read paths.
-- This fixes the constraint, and adds the CONTENT REQUIRED state so a missing
-- country variant is visible instead of silently serving the other country's text.
-- ============================================================

-- ------------------------------------------------------------
-- 1. UNIQUENESS THAT ACTUALLY HOLDS
-- ------------------------------------------------------------
alter table curriculum_days drop constraint if exists curriculum_days_version_id_day_no_country_override_key;

-- exactly one generic row per (version, day)
create unique index if not exists uq_cd_generic on curriculum_days (version_id, day_no)
  where country_override is null;
-- and at most one row per (version, day, country)
create unique index if not exists uq_cd_country on curriculum_days (version_id, day_no, country_override)
  where country_override is not null;

-- ------------------------------------------------------------
-- 2. CONTENT REQUIRED — never quietly use another country's content
-- ------------------------------------------------------------
alter table curriculum_days add column if not exists content_status text
  not null default 'ok' check (content_status in ('ok','draft','content_required'));
alter table curriculum_days add column if not exists content_owner text;
alter table curriculum_days add column if not exists content_note text;
comment on column curriculum_days.content_status is
  'ok = publishable. draft = being written. content_required = the STRUCTURE is defined but the authorised local legal/process content is missing. A content_required row is shown to admins and blocks nothing else — the generic row still serves the warrior, clearly labelled.';
comment on column curriculum_days.content_owner is
  'Who owns authoring this row (OPEN DECISION country_content_owner until Commander assigns it).';

-- ------------------------------------------------------------
-- 2b. ONE resolver for "which row does this warrior actually read?"
--     Country variant wins — but ONLY when it is publishable. A variant still
--     marked content_required falls back to the generic row, so a warrior is
--     never shown a placeholder and NEVER shown the other country's content.
-- ------------------------------------------------------------
create or replace function fn_curriculum_day(p_version uuid, p_day int, p_country country_t)
returns curriculum_days language sql stable security definer set search_path = public as $$
  select cd.* from curriculum_days cd
  where cd.version_id = p_version and cd.day_no = p_day
    and (cd.country_override is null
         or (cd.country_override = p_country and cd.content_status = 'ok'))
  order by (cd.country_override is null)      -- country-specific first, generic fallback
  limit 1;
$$;
grant execute on function fn_curriculum_day(uuid,int,country_t) to authenticated;

-- rewire the three read paths onto the resolver
create or replace function fn_submit_task(
  p_enrolment uuid, p_day int, p_response text, p_reflection text
) returns uuid language plpgsql security definer set search_path = public as $$
declare v_id uuid; v_cohort uuid; v_ver uuid; v_prev int; v_name text;
        v_open int; v_last text; v_country country_t; v_row curriculum_days;
begin
  select cohort_id into v_cohort from enrolments
  where id = p_enrolment and participant_id = auth.uid() and status = 'active';
  if v_cohort is null then raise exception 'enrolment not active or not yours'; end if;

  v_open := participant_accessible_day(p_enrolment);
  if p_day < 1 then raise exception 'invalid day %', p_day; end if;
  if p_day > v_open then
    raise exception 'day % is not open for you yet (your accessible day is %)', p_day, v_open;
  end if;

  select curriculum_version_id, country into v_ver, v_country from cohorts where id = v_cohort;
  v_row := fn_curriculum_day(v_ver, p_day, v_country);
  if v_row.id is null then raise exception 'day % is not published in this curriculum', p_day; end if;

  select status into v_last from task_submissions
   where enrolment_id = p_enrolment and day_no = p_day order by version desc limit 1;
  if v_last = 'approved' then raise exception 'day % is already approved', p_day; end if;

  select coalesce(max(version),0) into v_prev from task_submissions
  where enrolment_id = p_enrolment and day_no = p_day;
  insert into task_submissions (enrolment_id, day_id, day_no, status, response, reflection,
                                version, submitted_at, curriculum_version_id)
  values (p_enrolment, v_row.id, p_day, 'submitted', p_response, p_reflection, v_prev + 1, now(), v_ver)
  returning id into v_id;
  perform audit_log('task_submit','task_submission', v_id::text, null, 'submitted', 'day '||p_day||' v'||(v_prev+1));
  select name into v_name from profiles where id = auth.uid();
  perform notify_reviewers(auth.uid(), '📨 Day '||p_day||' evidence submitted',
    coalesce(v_name,'A warrior')||' submitted Day '||p_day||' (v'||(v_prev+1)||')', '#/coach');
  return v_id;
end $$;

create or replace function fn_day_proof(p_enrolment uuid, p_day int)
returns jsonb language plpgsql stable security definer set search_path = public as $$
declare v_p uuid; v_row curriculum_days; v_cfg jsonb; v_src text; v_min int; v_win int; v_have int;
begin
  -- NOTE: a composite must be its own INTO target — plpgsql treats every target in a
  -- multi-target SELECT INTO as a scalar, so this is deliberately two statements.
  select e.participant_id into v_p from enrolments e where e.id = p_enrolment;
  if v_p is null then return jsonb_build_object('applicable', false); end if;
  select fn_curriculum_day(c.curriculum_version_id, p_day, c.country) into v_row
  from enrolments e join cohorts c on c.id = e.cohort_id where e.id = p_enrolment;
  if v_row.proof_type is distinct from 'native_record' or v_row.proof_config is null then
    return jsonb_build_object('applicable', false, 'proof_type', v_row.proof_type);
  end if;
  v_cfg := v_row.proof_config;
  v_src := v_cfg->>'source';
  v_min := coalesce((v_cfg->>'min_count')::int, 1);
  v_win := coalesce((v_cfg->>'window_days')::int, 3650);
  v_have := case v_src
    when 'leads'        then (select count(*) from ch_leads l where l.participant_id = v_p and l.created_at > now() - make_interval(days => v_win))
    when 'activities'   then (select count(*) from ch_lead_activities a where a.participant_id = v_p and a.happened_at > now() - make_interval(days => v_win))
    when 'appointments' then (select count(*) from ch_appointments ap where ap.participant_id = v_p and ap.created_at > now() - make_interval(days => v_win))
    when 'closings'     then (select count(*) from ch_closings cl where cl.participant_id = v_p and cl.created_at > now() - make_interval(days => v_win))
    else 0 end;
  return jsonb_build_object('applicable', true, 'proof_type', v_row.proof_type, 'source', v_src,
    'required', v_min, 'have', v_have, 'satisfied', v_have >= v_min);
end $$;

-- ------------------------------------------------------------
-- 3. AUDIT THE EDITOR — curriculum edits were previously un-audited (§3)
-- ------------------------------------------------------------
create or replace function fn_admin_save_day(p_day uuid, p_patch jsonb)
returns void language plpgsql security definer set search_path = public as $$
declare v_no int; v_ver uuid; v_status text; v_used int;
begin
  if not has_role('super_admin') then raise exception 'not authorised'; end if;
  select day_no, version_id into v_no, v_ver from curriculum_days where id = p_day;
  if v_no is null then raise exception 'day not found'; end if;

  -- refuse to silently rewrite a day that warriors have already answered on a
  -- PUBLISHED version: that is what makes submissions un-auditable (§3).
  select status into v_status from curriculum_versions where id = v_ver;
  select count(*) into v_used from task_submissions where day_id = p_day;
  if v_status = 'published' and v_used > 0
     and (p_patch ? 'required_action' or p_patch ? 'evidence_requirement' or p_patch ? 'xp_amount') then
    raise exception 'Day % has % submission(s) answered against it. Publish a new curriculum version instead of changing what was already asked.', v_no, v_used;
  end if;

  update curriculum_days set
    title                = coalesce(p_patch->'title', title),
    objective            = coalesce(p_patch->'objective', objective),
    content              = coalesce(p_patch->'content', content),
    instructions         = coalesce(p_patch->'instructions', instructions),
    required_action      = coalesce(p_patch->'required_action', required_action),
    stretch_action       = coalesce(p_patch->'stretch_action', stretch_action),
    evidence_requirement = coalesce(p_patch->'evidence_requirement', evidence_requirement),
    reflection_question  = coalesce(p_patch->'reflection_question', reflection_question),
    coach_guidance       = coalesce(p_patch->'coach_guidance', coach_guidance),
    media_url            = coalesce(p_patch->>'media_url', media_url),
    xp_amount            = coalesce((p_patch->>'xp_amount')::int, xp_amount),
    needs_review         = coalesce((p_patch->>'needs_review')::boolean, needs_review),
    proof_type           = coalesce(p_patch->>'proof_type', proof_type),
    proof_config         = coalesce(p_patch->'proof_config', proof_config),
    content_status       = coalesce(p_patch->>'content_status', content_status),
    content_owner        = coalesce(p_patch->>'content_owner', content_owner),
    content_note         = coalesce(p_patch->>'content_note', content_note)
  where id = p_day;

  perform audit_log('curriculum_day_edited','curriculum_day', p_day::text, null,
    'day ' || v_no, (select string_agg(k, ', ') from jsonb_object_keys(p_patch) k));
end $$;
grant execute on function fn_admin_save_day(uuid,jsonb) to authenticated;

-- ------------------------------------------------------------
-- 4. VERSION LIFECYCLE — the missing admin capability (audit §14)
-- ------------------------------------------------------------
create or replace function fn_admin_new_version(p_from uuid, p_note text)
returns uuid language plpgsql security definer set search_path = public as $$
declare v_new uuid; v_prog uuid; v_next int;
begin
  if not has_role('super_admin') then raise exception 'not authorised'; end if;
  select program_id into v_prog from curriculum_versions where id = p_from;
  if v_prog is null then raise exception 'source version not found'; end if;
  select coalesce(max(version),0) + 1 into v_next from curriculum_versions where program_id = v_prog;
  insert into curriculum_versions (program_id, version, status, created_by)
  values (v_prog, v_next, 'draft', auth.uid()) returning id into v_new;
  -- deep copy every day, country variants included
  insert into curriculum_days (version_id, day_no, phase, title, objective, content, instructions,
    required_action, stretch_action, evidence_requirement, reflection_question, coach_guidance,
    media_url, xp_amount, needs_review, country_override, proof_type, proof_config,
    content_status, content_owner, content_note)
  select v_new, day_no, phase, title, objective, content, instructions,
    required_action, stretch_action, evidence_requirement, reflection_question, coach_guidance,
    media_url, xp_amount, needs_review, country_override, proof_type, proof_config,
    content_status, content_owner, content_note
  from curriculum_days where version_id = p_from;
  perform audit_log('curriculum_version_created','curriculum_version', v_new::text, null, 'draft v'||v_next, p_note);
  return v_new;
end $$;
grant execute on function fn_admin_new_version(uuid,text) to authenticated;

create or replace function fn_admin_publish_version(p_version uuid, p_note text)
returns void language plpgsql security definer set search_path = public as $$
declare v_days int; v_missing int; v_prev text;
begin
  if not has_role('super_admin') then raise exception 'not authorised'; end if;
  select status into v_prev from curriculum_versions where id = p_version;
  if v_prev is null then raise exception 'not found'; end if;
  select count(*) into v_days from curriculum_days where version_id = p_version and country_override is null;
  if v_days <> 30 then raise exception 'this version has % generic days, expected 30', v_days; end if;
  select count(*) into v_missing from curriculum_days
   where version_id = p_version and content_status = 'draft';
  if v_missing > 0 then raise exception '% day(s) are still marked draft', v_missing; end if;
  update curriculum_versions set status = 'published', published_at = now() where id = p_version;
  perform audit_log('curriculum_published','curriculum_version', p_version::text, v_prev, 'published', p_note);
end $$;
grant execute on function fn_admin_publish_version(uuid,text) to authenticated;

-- which days are waiting on authorised local content? (Admin surface)
create or replace function fn_content_gaps(p_version uuid default null)
returns table (version_id uuid, version int, day_no int, country text,
               content_status text, content_owner text, content_note text, title jsonb)
language sql stable security definer set search_path = public as $$
  select cd.version_id, cv.version, cd.day_no, coalesce(cd.country_override::text,'GENERIC'),
         cd.content_status, cd.content_owner, cd.content_note, cd.title
  from curriculum_days cd join curriculum_versions cv on cv.id = cd.version_id
  where cd.content_status <> 'ok'
    and (p_version is null or cd.version_id = p_version)
    and auth.uid() is not null
  order by cv.version desc, cd.day_no, cd.country_override nulls first;
$$;
grant execute on function fn_content_gaps(uuid) to authenticated;

-- ------------------------------------------------------------
-- 4b. Today's mission must read the same resolved row as the submit path,
--     or a warrior could read one variant and answer against another.
-- ------------------------------------------------------------
create or replace function fn_daily_mission(p_enrolment uuid)
returns jsonb language plpgsql stable security definer set search_path = public as $$
declare
  v_p uuid; v_cohort uuid; v_day int; v_today date; v_row curriculum_days;
  v_ver uuid; v_country country_t;
  v_new_today int; v_due int; v_cleared int; v_active int; v_no_next int;
  v_sub text; v_pri jsonb; v_appt_soon int; v_view_no_fu int; v_qual_no_appt int;
begin
  select e.participant_id, e.cohort_id into v_p, v_cohort from enrolments e where e.id = p_enrolment;
  if v_p is null then raise exception 'not found'; end if;
  if not (v_p = auth.uid() or is_reviewer_of(v_p)) then raise exception 'not authorised'; end if;

  v_day   := participant_accessible_day(p_enrolment);
  v_today := cohort_local_date(v_cohort);
  select curriculum_version_id, country into v_ver, v_country from cohorts where id = v_cohort;
  v_row := fn_curriculum_day(v_ver, greatest(v_day, 1), v_country);

  select status into v_sub from task_submissions
   where enrolment_id = p_enrolment and day_no = v_day order by version desc limit 1;

  select count(*) into v_new_today from ch_leads
   where participant_id = v_p and created_at >= v_today::timestamptz;
  select count(*) into v_due from ch_leads
   where participant_id = v_p and next_action_at is not null and next_action_at <= v_today
     and stage not in ('CLOSED_WON','CLOSED_LOST','DISQUALIFIED');
  select count(*) into v_cleared from ch_lead_activities
   where participant_id = v_p and happened_at >= v_today::timestamptz;
  select count(*) into v_active from ch_leads
   where participant_id = v_p and stage not in ('CLOSED_WON','CLOSED_LOST','DISQUALIFIED','NURTURE');
  select count(*) into v_no_next from ch_leads
   where participant_id = v_p and next_action_at is null
     and stage not in ('CLOSED_WON','CLOSED_LOST','DISQUALIFIED','NURTURE');

  select count(*) into v_appt_soon from ch_appointments
   where participant_id = v_p and status in ('SCHEDULED','CONFIRMED')
     and starts_at between now() and now() + interval '36 hours';
  select count(*) into v_view_no_fu from ch_appointments ap
   where ap.participant_id = v_p and ap.status = 'COMPLETED'
     and not exists (select 1 from ch_lead_activities a
                     where a.lead_id = ap.lead_id and a.happened_at > ap.starts_at);
  select count(*) into v_qual_no_appt from ch_leads l
   where l.participant_id = v_p and l.stage = 'QUALIFIED'
     and not exists (select 1 from ch_appointments ap where ap.lead_id = l.id);

  v_pri := case
    when v_appt_soon  > 0 then jsonb_build_object('code','VIEWING_PREP','count',v_appt_soon,'link','#/pipeline')
    when v_view_no_fu > 0 then jsonb_build_object('code','POST_VIEWING_FOLLOW_UP','count',v_view_no_fu,'link','#/pipeline')
    when v_due        > 0 then jsonb_build_object('code','FOLLOW_UPS_DUE','count',v_due,'link','#/pipeline')
    when v_qual_no_appt > 0 then jsonb_build_object('code','SET_APPOINTMENT','count',v_qual_no_appt,'link','#/pipeline')
    else null end;

  return jsonb_build_object(
    'enrolment_id', p_enrolment,
    'local_date', v_today,
    'cohort_day', cohort_day(v_cohort),
    'accessible_day', v_day,
    'curriculum', case when v_row.id is null then null else jsonb_build_object(
        'day_no', v_row.day_no, 'phase', v_row.phase, 'title', v_row.title,
        'objective', v_row.objective, 'xp_amount', v_row.xp_amount,
        'proof_type', v_row.proof_type, 'country_variant', v_row.country_override,
        'status', coalesce(v_sub,'not_started')) end,
    'proof', fn_day_proof(p_enrolment, greatest(v_day,1)),
    'business', jsonb_build_object(
        'new_conversations', v_new_today,
        'followups_due', v_due,
        'touches_today', v_cleared,
        'active_leads', v_active,
        'leads_without_next_action', v_no_next),
    'targets', jsonb_strip_nulls(jsonb_build_object(
        'new_conversations', fn_target(v_cohort,'new_conversations'),
        'followups_cleared', fn_target(v_cohort,'followups_cleared'),
        'active_leads_with_next_action', fn_target(v_cohort,'active_leads_with_next_action'))),
    'priority', v_pri);
end $$;

-- ------------------------------------------------------------
-- 5. VERIFY
-- ------------------------------------------------------------
select 'generic days per version (each must be 30 or 0)' as check,
       cv.version, count(*) filter (where cd.country_override is null) as generic,
       count(*) filter (where cd.country_override is not null) as country_variants
from curriculum_versions cv left join curriculum_days cd on cd.version_id = cv.id
group by cv.version order by cv.version;
