-- ============================================================
-- 086_notification_content.sql — GENERATED by tools/notification_templates.py
-- Do not hand-edit; edit the generator or the templates in Command HQ.
--
-- 1. Seeds every controlled 30 Days notification template (v1, published).
-- 2. Rewires the challenge functions onto managed content.
-- 3. Assigns Kamal as tary's Coach through the audited domain path.
--
-- COUNTRY FIRST: MY and ID each carry their own two locales, including their
-- own English row. No cross-country fallback is possible by construction.
-- ============================================================

do $seed$
declare v_ver uuid;
begin
  -- invitation: Warrior invited to join Hero
  insert into ch_notification_templates (code, purpose, audience, notify_type, variables, status)
  values ('invitation', 'Warrior invited to join Hero', 'participant', 'invitation', array['participant_name','cohort_name']::text[], 'active')
  on conflict (code) do nothing;
  insert into ch_notification_template_versions (template_code, version, status, published_at)
  values ('invitation', 1, 'published', now())
  on conflict (template_code, version) do nothing
  returning id into v_ver;
  if v_ver is null then select id into v_ver from ch_notification_template_versions
    where template_code = 'invitation' and version = 1; end if;
  insert into ch_notification_template_translations (version_id, country, locale, title, body) values
    (v_ver, 'MY', 'ms-MY', '🛡 Jemputan ke IQI AG Hero', 'Anda dijemput menyertai {{cohort_name}}. Buka Hero untuk menerima jemputan dan mula.'),
    (v_ver, 'MY', 'en', '🛡 You are invited to IQI AG Hero', 'You have been invited to join {{cohort_name}}. Open Hero to accept and begin.'),
    (v_ver, 'ID', 'id-ID', '🛡 Undangan ke IQI AG Hero', 'Anda diundang bergabung {{cohort_name}}. Buka Hero untuk menerima undangan dan mulai.'),
    (v_ver, 'ID', 'en', '🛡 You are invited to IQI AG Hero', 'You have been invited to join {{cohort_name}}. Open Hero to accept and begin.')
  on conflict (version_id, country, locale) do nothing;

  -- invitation_accepted: Inviter told their invite was accepted
  insert into ch_notification_templates (code, purpose, audience, notify_type, variables, status)
  values ('invitation_accepted', 'Inviter told their invite was accepted', 'coach', 'invitation', array['participant_name','cohort_name']::text[], 'active')
  on conflict (code) do nothing;
  insert into ch_notification_template_versions (template_code, version, status, published_at)
  values ('invitation_accepted', 1, 'published', now())
  on conflict (template_code, version) do nothing
  returning id into v_ver;
  if v_ver is null then select id into v_ver from ch_notification_template_versions
    where template_code = 'invitation_accepted' and version = 1; end if;
  insert into ch_notification_template_translations (version_id, country, locale, title, body) values
    (v_ver, 'MY', 'ms-MY', '🎉 Jemputan diterima', '{{participant_name}} telah menyertai IQI AG Hero.'),
    (v_ver, 'MY', 'en', '🎉 Invitation accepted', '{{participant_name}} has joined IQI AG Hero.'),
    (v_ver, 'ID', 'id-ID', '🎉 Undangan diterima', '{{participant_name}} telah bergabung dengan IQI AG Hero.'),
    (v_ver, 'ID', 'en', '🎉 Invitation accepted', '{{participant_name}} has joined IQI AG Hero.')
  on conflict (version_id, country, locale) do nothing;

  -- enrolled: Admin enrolled a warrior into a cohort
  insert into ch_notification_templates (code, purpose, audience, notify_type, variables, status)
  values ('enrolled', 'Admin enrolled a warrior into a cohort', 'participant', 'challenge', array['participant_name','cohort_name']::text[], 'active')
  on conflict (code) do nothing;
  insert into ch_notification_template_versions (template_code, version, status, published_at)
  values ('enrolled', 1, 'published', now())
  on conflict (template_code, version) do nothing
  returning id into v_ver;
  if v_ver is null then select id into v_ver from ch_notification_template_versions
    where template_code = 'enrolled' and version = 1; end if;
  insert into ch_notification_template_translations (version_id, country, locale, title, body) values
    (v_ver, 'MY', 'ms-MY', '🎯 Anda didaftarkan: Cabaran Closing 30 Hari', 'Kohort {{cohort_name}}. Buka cabaran untuk melengkapkan onboarding dan kesediaan anda.'),
    (v_ver, 'MY', 'en', '🎯 You are enrolled: 30 Days Closing Challenge', 'Cohort {{cohort_name}}. Open the challenge to complete your onboarding and readiness.'),
    (v_ver, 'ID', 'id-ID', '🎯 Anda terdaftar: Tantangan Closing 30 Hari', 'Cohort {{cohort_name}}. Buka tantangan untuk menyelesaikan onboarding dan kesiapan Anda.'),
    (v_ver, 'ID', 'en', '🎯 You are enrolled: 30 Days Closing Challenge', 'Cohort {{cohort_name}}. Open the challenge to complete your onboarding and readiness.')
  on conflict (version_id, country, locale) do nothing;

  -- onboarding_incomplete: Enrolled but readiness not submitted
  insert into ch_notification_templates (code, purpose, audience, notify_type, variables, status)
  values ('onboarding_incomplete', 'Enrolled but readiness not submitted', 'participant', 'challenge', array['participant_name']::text[], 'active')
  on conflict (code) do nothing;
  insert into ch_notification_template_versions (template_code, version, status, published_at)
  values ('onboarding_incomplete', 1, 'published', now())
  on conflict (template_code, version) do nothing
  returning id into v_ver;
  if v_ver is null then select id into v_ver from ch_notification_template_versions
    where template_code = 'onboarding_incomplete' and version = 1; end if;
  insert into ch_notification_template_translations (version_id, country, locale, title, body) values
    (v_ver, 'MY', 'ms-MY', '📋 Kesediaan anda belum dihantar', 'Lengkapkan onboarding dan hantar kesediaan anda untuk membuka Hari 1.'),
    (v_ver, 'MY', 'en', '📋 Your readiness is not submitted yet', 'Complete your onboarding and submit your readiness to open Day 1.'),
    (v_ver, 'ID', 'id-ID', '📋 Kesiapan Anda belum dikirim', 'Selesaikan onboarding dan kirim kesiapan Anda untuk membuka Hari 1.'),
    (v_ver, 'ID', 'en', '📋 Your readiness is not submitted yet', 'Complete your onboarding and submit your readiness to open Day 1.')
  on conflict (version_id, country, locale) do nothing;

  -- readiness_submitted: Reviewer told readiness is waiting
  insert into ch_notification_templates (code, purpose, audience, notify_type, variables, status)
  values ('readiness_submitted', 'Reviewer told readiness is waiting', 'coach', 'review', array['participant_name']::text[], 'active')
  on conflict (code) do nothing;
  insert into ch_notification_template_versions (template_code, version, status, published_at)
  values ('readiness_submitted', 1, 'published', now())
  on conflict (template_code, version) do nothing
  returning id into v_ver;
  if v_ver is null then select id into v_ver from ch_notification_template_versions
    where template_code = 'readiness_submitted' and version = 1; end if;
  insert into ch_notification_template_translations (version_id, country, locale, title, body) values
    (v_ver, 'MY', 'ms-MY', '📨 Kesediaan dihantar', '{{participant_name}} menghantar kesediaan untuk semakan.'),
    (v_ver, 'MY', 'en', '📨 Readiness submitted', '{{participant_name}} submitted readiness for review.'),
    (v_ver, 'ID', 'id-ID', '📨 Kesiapan dikirim', '{{participant_name}} mengirim kesiapan untuk ditinjau.'),
    (v_ver, 'ID', 'en', '📨 Readiness submitted', '{{participant_name}} submitted readiness for review.')
  on conflict (version_id, country, locale) do nothing;

  -- readiness_approved: Readiness approved, warrior is ACTIVE
  insert into ch_notification_templates (code, purpose, audience, notify_type, variables, status)
  values ('readiness_approved', 'Readiness approved, warrior is ACTIVE', 'participant', 'readiness', array['coach_name','review_note']::text[], 'active')
  on conflict (code) do nothing;
  insert into ch_notification_template_versions (template_code, version, status, published_at)
  values ('readiness_approved', 1, 'published', now())
  on conflict (template_code, version) do nothing
  returning id into v_ver;
  if v_ver is null then select id into v_ver from ch_notification_template_versions
    where template_code = 'readiness_approved' and version = 1; end if;
  insert into ch_notification_template_translations (version_id, country, locale, title, body) values
    (v_ver, 'MY', 'ms-MY', '✅ Kesediaan diluluskan', 'Anda kini AKTIF. Hari 1 sudah terbuka.'),
    (v_ver, 'MY', 'en', '✅ Readiness approved', 'You are now ACTIVE. Day 1 is open.'),
    (v_ver, 'ID', 'id-ID', '✅ Kesiapan disetujui', 'Anda kini AKTIF. Hari 1 sudah terbuka.'),
    (v_ver, 'ID', 'en', '✅ Readiness approved', 'You are now ACTIVE. Day 1 is open.')
  on conflict (version_id, country, locale) do nothing;

  -- readiness_revision: Readiness sent back
  insert into ch_notification_templates (code, purpose, audience, notify_type, variables, status)
  values ('readiness_revision', 'Readiness sent back', 'participant', 'readiness', array['review_note']::text[], 'active')
  on conflict (code) do nothing;
  insert into ch_notification_template_versions (template_code, version, status, published_at)
  values ('readiness_revision', 1, 'published', now())
  on conflict (template_code, version) do nothing
  returning id into v_ver;
  if v_ver is null then select id into v_ver from ch_notification_template_versions
    where template_code = 'readiness_revision' and version = 1; end if;
  insert into ch_notification_template_translations (version_id, country, locale, title, body) values
    (v_ver, 'MY', 'ms-MY', '🔄 Kesediaan — perlu semakan semula', '{{review_note}}'),
    (v_ver, 'MY', 'en', '🔄 Readiness — revision required', '{{review_note}}'),
    (v_ver, 'ID', 'id-ID', '🔄 Kesiapan — perlu revisi', '{{review_note}}'),
    (v_ver, 'ID', 'en', '🔄 Readiness — revision required', '{{review_note}}')
  on conflict (version_id, country, locale) do nothing;

  -- new_day_available: A new curriculum day opened
  insert into ch_notification_templates (code, purpose, audience, notify_type, variables, status)
  values ('new_day_available', 'A new curriculum day opened', 'participant', 'challenge', array['challenge_day','day_title']::text[], 'active')
  on conflict (code) do nothing;
  insert into ch_notification_template_versions (template_code, version, status, published_at)
  values ('new_day_available', 1, 'published', now())
  on conflict (template_code, version) do nothing
  returning id into v_ver;
  if v_ver is null then select id into v_ver from ch_notification_template_versions
    where template_code = 'new_day_available' and version = 1; end if;
  insert into ch_notification_template_translations (version_id, country, locale, title, body) values
    (v_ver, 'MY', 'ms-MY', '📖 Hari {{challenge_day}} sudah terbuka', '{{day_title}}. Buka Hero untuk mula.'),
    (v_ver, 'MY', 'en', '📖 Day {{challenge_day}} is open', '{{day_title}}. Open Hero to begin.'),
    (v_ver, 'ID', 'id-ID', '📖 Hari {{challenge_day}} sudah terbuka', '{{day_title}}. Buka Hero untuk mulai.'),
    (v_ver, 'ID', 'en', '📖 Day {{challenge_day}} is open', '{{day_title}}. Open Hero to begin.')
  on conflict (version_id, country, locale) do nothing;

  -- daily_reminder: Daily nudge to act
  insert into ch_notification_templates (code, purpose, audience, notify_type, variables, status)
  values ('daily_reminder', 'Daily nudge to act', 'participant', 'challenge', array['challenge_day']::text[], 'active')
  on conflict (code) do nothing;
  insert into ch_notification_template_versions (template_code, version, status, published_at)
  values ('daily_reminder', 1, 'published', now())
  on conflict (template_code, version) do nothing
  returning id into v_ver;
  if v_ver is null then select id into v_ver from ch_notification_template_versions
    where template_code = 'daily_reminder' and version = 1; end if;
  insert into ch_notification_template_translations (version_id, country, locale, title, body) values
    (v_ver, 'MY', 'ms-MY', '⏱ Hari {{challenge_day}} masih menunggu', 'Buka Hero untuk lihat misi hari ini dan susulan yang perlu.'),
    (v_ver, 'MY', 'en', '⏱ Day {{challenge_day}} is still waiting', 'Open Hero to see today’s mission and the follow-ups that are due.'),
    (v_ver, 'ID', 'id-ID', '⏱ Hari {{challenge_day}} masih menunggu', 'Buka Hero untuk melihat misi hari ini dan follow-up yang jatuh tempo.'),
    (v_ver, 'ID', 'en', '⏱ Day {{challenge_day}} is still waiting', 'Open Hero to see today’s mission and the follow-ups that are due.')
  on conflict (version_id, country, locale) do nothing;

  -- due_soon: Something is due today
  insert into ch_notification_templates (code, purpose, audience, notify_type, variables, status)
  values ('due_soon', 'Something is due today', 'participant', 'challenge', array['due_date','next_action']::text[], 'active')
  on conflict (code) do nothing;
  insert into ch_notification_template_versions (template_code, version, status, published_at)
  values ('due_soon', 1, 'published', now())
  on conflict (template_code, version) do nothing
  returning id into v_ver;
  if v_ver is null then select id into v_ver from ch_notification_template_versions
    where template_code = 'due_soon' and version = 1; end if;
  insert into ch_notification_template_translations (version_id, country, locale, title, body) values
    (v_ver, 'MY', 'ms-MY', '📅 Perlu diselesaikan {{due_date}}', '{{next_action}}'),
    (v_ver, 'MY', 'en', '📅 Due {{due_date}}', '{{next_action}}'),
    (v_ver, 'ID', 'id-ID', '📅 Jatuh tempo {{due_date}}', '{{next_action}}'),
    (v_ver, 'ID', 'en', '📅 Due {{due_date}}', '{{next_action}}')
  on conflict (version_id, country, locale) do nothing;

  -- task_submitted: Reviewer told evidence is waiting
  insert into ch_notification_templates (code, purpose, audience, notify_type, variables, status)
  values ('task_submitted', 'Reviewer told evidence is waiting', 'coach', 'review', array['participant_name','challenge_day','version']::text[], 'active')
  on conflict (code) do nothing;
  insert into ch_notification_template_versions (template_code, version, status, published_at)
  values ('task_submitted', 1, 'published', now())
  on conflict (template_code, version) do nothing
  returning id into v_ver;
  if v_ver is null then select id into v_ver from ch_notification_template_versions
    where template_code = 'task_submitted' and version = 1; end if;
  insert into ch_notification_template_translations (version_id, country, locale, title, body) values
    (v_ver, 'MY', 'ms-MY', '📨 Bukti Hari {{challenge_day}} dihantar', '{{participant_name}} menghantar Hari {{challenge_day}} (v{{version}}).'),
    (v_ver, 'MY', 'en', '📨 Day {{challenge_day}} evidence submitted', '{{participant_name}} submitted Day {{challenge_day}} (v{{version}}).'),
    (v_ver, 'ID', 'id-ID', '📨 Bukti Hari {{challenge_day}} dikirim', '{{participant_name}} mengirim Hari {{challenge_day}} (v{{version}}).'),
    (v_ver, 'ID', 'en', '📨 Day {{challenge_day}} evidence submitted', '{{participant_name}} submitted Day {{challenge_day}} (v{{version}}).')
  on conflict (version_id, country, locale) do nothing;

  -- evidence_approved: Day approved, XP written
  insert into ch_notification_templates (code, purpose, audience, notify_type, variables, status)
  values ('evidence_approved', 'Day approved, XP written', 'participant', 'evidence', array['challenge_day','xp_amount','review_note']::text[], 'active')
  on conflict (code) do nothing;
  insert into ch_notification_template_versions (template_code, version, status, published_at)
  values ('evidence_approved', 1, 'published', now())
  on conflict (template_code, version) do nothing
  returning id into v_ver;
  if v_ver is null then select id into v_ver from ch_notification_template_versions
    where template_code = 'evidence_approved' and version = 1; end if;
  insert into ch_notification_template_translations (version_id, country, locale, title, body) values
    (v_ver, 'MY', 'ms-MY', '🏆 Hari {{challenge_day}} diluluskan — +{{xp_amount}} XP', 'XP disahkan direkod ke lejar anda. {{review_note}}'),
    (v_ver, 'MY', 'en', '🏆 Day {{challenge_day}} approved — +{{xp_amount}} XP', 'Verified XP written to your ledger. {{review_note}}'),
    (v_ver, 'ID', 'id-ID', '🏆 Hari {{challenge_day}} disetujui — +{{xp_amount}} XP', 'XP terverifikasi dicatat ke buku besar Anda. {{review_note}}'),
    (v_ver, 'ID', 'en', '🏆 Day {{challenge_day}} approved — +{{xp_amount}} XP', 'Verified XP written to your ledger. {{review_note}}')
  on conflict (version_id, country, locale) do nothing;

  -- evidence_approved_no_xp: Approved again, already credited
  insert into ch_notification_templates (code, purpose, audience, notify_type, variables, status)
  values ('evidence_approved_no_xp', 'Approved again, already credited', 'participant', 'evidence', array['challenge_day','review_note']::text[], 'active')
  on conflict (code) do nothing;
  insert into ch_notification_template_versions (template_code, version, status, published_at)
  values ('evidence_approved_no_xp', 1, 'published', now())
  on conflict (template_code, version) do nothing
  returning id into v_ver;
  if v_ver is null then select id into v_ver from ch_notification_template_versions
    where template_code = 'evidence_approved_no_xp' and version = 1; end if;
  insert into ch_notification_template_translations (version_id, country, locale, title, body) values
    (v_ver, 'MY', 'ms-MY', '✅ Hari {{challenge_day}} diluluskan', 'Hari ini sudah dikreditkan sebelum ini — tiada XP berganda. {{review_note}}'),
    (v_ver, 'MY', 'en', '✅ Day {{challenge_day}} approved', 'This day was already credited — no duplicate XP. {{review_note}}'),
    (v_ver, 'ID', 'id-ID', '✅ Hari {{challenge_day}} disetujui', 'Hari ini sudah dikreditkan sebelumnya — tidak ada XP ganda. {{review_note}}'),
    (v_ver, 'ID', 'en', '✅ Day {{challenge_day}} approved', 'This day was already credited — no duplicate XP. {{review_note}}')
  on conflict (version_id, country, locale) do nothing;

  -- evidence_revision: Day sent back for revision
  insert into ch_notification_templates (code, purpose, audience, notify_type, variables, status)
  values ('evidence_revision', 'Day sent back for revision', 'participant', 'evidence', array['challenge_day','review_note']::text[], 'active')
  on conflict (code) do nothing;
  insert into ch_notification_template_versions (template_code, version, status, published_at)
  values ('evidence_revision', 1, 'published', now())
  on conflict (template_code, version) do nothing
  returning id into v_ver;
  if v_ver is null then select id into v_ver from ch_notification_template_versions
    where template_code = 'evidence_revision' and version = 1; end if;
  insert into ch_notification_template_translations (version_id, country, locale, title, body) values
    (v_ver, 'MY', 'ms-MY', '🔄 Hari {{challenge_day}} — perlu semakan semula', '{{review_note}} Penghantaran asal anda dikekalkan.'),
    (v_ver, 'MY', 'en', '🔄 Day {{challenge_day}} — revision required', '{{review_note}} Your original submission is preserved.'),
    (v_ver, 'ID', 'id-ID', '🔄 Hari {{challenge_day}} — perlu revisi', '{{review_note}} Pengiriman asli Anda tetap disimpan.'),
    (v_ver, 'ID', 'en', '🔄 Day {{challenge_day}} — revision required', '{{review_note}} Your original submission is preserved.')
  on conflict (version_id, country, locale) do nothing;

  -- evidence_rejected: Day not accepted
  insert into ch_notification_templates (code, purpose, audience, notify_type, variables, status)
  values ('evidence_rejected', 'Day not accepted', 'participant', 'evidence', array['challenge_day','review_note']::text[], 'active')
  on conflict (code) do nothing;
  insert into ch_notification_template_versions (template_code, version, status, published_at)
  values ('evidence_rejected', 1, 'published', now())
  on conflict (template_code, version) do nothing
  returning id into v_ver;
  if v_ver is null then select id into v_ver from ch_notification_template_versions
    where template_code = 'evidence_rejected' and version = 1; end if;
  insert into ch_notification_template_translations (version_id, country, locale, title, body) values
    (v_ver, 'MY', 'ms-MY', '⛔ Hari {{challenge_day}} — tidak diterima', '{{review_note}} Penghantaran asal anda dikekalkan.'),
    (v_ver, 'MY', 'en', '⛔ Day {{challenge_day}} — not accepted', '{{review_note}} Your original submission is preserved.'),
    (v_ver, 'ID', 'id-ID', '⛔ Hari {{challenge_day}} — tidak diterima', '{{review_note}} Pengiriman asli Anda tetap disimpan.'),
    (v_ver, 'ID', 'en', '⛔ Day {{challenge_day}} — not accepted', '{{review_note}} Your original submission is preserved.')
  on conflict (version_id, country, locale) do nothing;

  -- coaching_report_shared: Coach shared a written report
  insert into ch_notification_templates (code, purpose, audience, notify_type, variables, status)
  values ('coaching_report_shared', 'Coach shared a written report', 'participant', 'coaching', array['coach_name','period']::text[], 'active')
  on conflict (code) do nothing;
  insert into ch_notification_template_versions (template_code, version, status, published_at)
  values ('coaching_report_shared', 1, 'published', now())
  on conflict (template_code, version) do nothing
  returning id into v_ver;
  if v_ver is null then select id into v_ver from ch_notification_template_versions
    where template_code = 'coaching_report_shared' and version = 1; end if;
  insert into ch_notification_template_translations (version_id, country, locale, title, body) values
    (v_ver, 'MY', 'ms-MY', '🧭 Laporan coaching baharu', '{{coach_name}} berkongsi laporan {{period}} anda. Buka untuk baca dan akui.'),
    (v_ver, 'MY', 'en', '🧭 New coaching report', '{{coach_name}} shared your {{period}} report. Open it to read and acknowledge.'),
    (v_ver, 'ID', 'id-ID', '🧭 Laporan coaching baru', '{{coach_name}} membagikan laporan {{period}} Anda. Buka untuk membaca dan mengakui.'),
    (v_ver, 'ID', 'en', '🧭 New coaching report', '{{coach_name}} shared your {{period}} report. Open it to read and acknowledge.')
  on conflict (version_id, country, locale) do nothing;

  -- report_acknowledged: Participant acknowledged the report
  insert into ch_notification_templates (code, purpose, audience, notify_type, variables, status)
  values ('report_acknowledged', 'Participant acknowledged the report', 'coach', 'coaching', array['participant_name']::text[], 'active')
  on conflict (code) do nothing;
  insert into ch_notification_template_versions (template_code, version, status, published_at)
  values ('report_acknowledged', 1, 'published', now())
  on conflict (template_code, version) do nothing
  returning id into v_ver;
  if v_ver is null then select id into v_ver from ch_notification_template_versions
    where template_code = 'report_acknowledged' and version = 1; end if;
  insert into ch_notification_template_translations (version_id, country, locale, title, body) values
    (v_ver, 'MY', 'ms-MY', '✅ Laporan diakui', '{{participant_name}} telah membaca dan mengakui laporan anda.'),
    (v_ver, 'MY', 'en', '✅ Report acknowledged', '{{participant_name}} has read and acknowledged your report.'),
    (v_ver, 'ID', 'id-ID', '✅ Laporan diakui', '{{participant_name}} telah membaca dan mengakui laporan Anda.'),
    (v_ver, 'ID', 'en', '✅ Report acknowledged', '{{participant_name}} has read and acknowledged your report.')
  on conflict (version_id, country, locale) do nothing;

  -- followup_overdue: Agreed follow-up date has passed
  insert into ch_notification_templates (code, purpose, audience, notify_type, variables, status)
  values ('followup_overdue', 'Agreed follow-up date has passed', 'participant', 'challenge', array['count']::text[], 'active')
  on conflict (code) do nothing;
  insert into ch_notification_template_versions (template_code, version, status, published_at)
  values ('followup_overdue', 1, 'published', now())
  on conflict (template_code, version) do nothing
  returning id into v_ver;
  if v_ver is null then select id into v_ver from ch_notification_template_versions
    where template_code = 'followup_overdue' and version = 1; end if;
  insert into ch_notification_template_translations (version_id, country, locale, title, body) values
    (v_ver, 'MY', 'ms-MY', '⏰ Susulan tertunggak', 'Tarikh susulan yang dijanjikan sudah berlalu. Membersihkannya selalunya menggerakkan pipeline lebih daripada lead baharu.'),
    (v_ver, 'MY', 'en', '⏰ Overdue follow-up', 'Some agreed follow-up dates have passed. Clearing them usually moves the pipeline more than new leads do.'),
    (v_ver, 'ID', 'id-ID', '⏰ Follow-up terlambat', 'Tanggal follow-up yang dijanjikan sudah lewat. Menyelesaikannya biasanya menggerakkan pipeline lebih dari lead baru.'),
    (v_ver, 'ID', 'en', '⏰ Overdue follow-up', 'Some agreed follow-up dates have passed. Clearing them usually moves the pipeline more than new leads do.')
  on conflict (version_id, country, locale) do nothing;

  -- inactivity_nudge: No CRM activity for 2+ days
  insert into ch_notification_templates (code, purpose, audience, notify_type, variables, status)
  values ('inactivity_nudge', 'No CRM activity for 2+ days', 'participant', 'challenge', '{}'::text[], 'active')
  on conflict (code) do nothing;
  insert into ch_notification_template_versions (template_code, version, status, published_at)
  values ('inactivity_nudge', 1, 'published', now())
  on conflict (template_code, version) do nothing
  returning id into v_ver;
  if v_ver is null then select id into v_ver from ch_notification_template_versions
    where template_code = 'inactivity_nudge' and version = 1; end if;
  insert into ch_notification_template_translations (version_id, country, locale, title, body) values
    (v_ver, 'MY', 'ms-MY', '👋 Pipeline anda sunyi', 'Tiada perbualan direkod selama dua hari. Satu perbualan sebenar hari ini mengekalkan momentum.'),
    (v_ver, 'MY', 'en', '👋 Your pipeline has been quiet', 'No conversations logged for two days. One real conversation today keeps the momentum.'),
    (v_ver, 'ID', 'id-ID', '👋 Pipeline Anda sepi', 'Tidak ada percakapan tercatat selama dua hari. Satu percakapan nyata hari ini menjaga momentum.'),
    (v_ver, 'ID', 'en', '👋 Your pipeline has been quiet', 'No conversations logged for two days. One real conversation today keeps the momentum.')
  on conflict (version_id, country, locale) do nothing;

  -- inactivity_coach: Coach told a warrior is inactive
  insert into ch_notification_templates (code, purpose, audience, notify_type, variables, status)
  values ('inactivity_coach', 'Coach told a warrior is inactive', 'coach', 'review', array['participant_name']::text[], 'active')
  on conflict (code) do nothing;
  insert into ch_notification_template_versions (template_code, version, status, published_at)
  values ('inactivity_coach', 1, 'published', now())
  on conflict (template_code, version) do nothing
  returning id into v_ver;
  if v_ver is null then select id into v_ver from ch_notification_template_versions
    where template_code = 'inactivity_coach' and version = 1; end if;
  insert into ch_notification_template_translations (version_id, country, locale, title, body) values
    (v_ver, 'MY', 'ms-MY', '⚠ {{participant_name}} tidak aktif 2 hari+', 'Tiada aktiviti CRM direkod. Semakan ringkas selalunya memulihkannya.'),
    (v_ver, 'MY', 'en', '⚠ {{participant_name}} has been inactive 2+ days', 'No CRM activity logged. A short check-in usually turns this around.'),
    (v_ver, 'ID', 'id-ID', '⚠ {{participant_name}} tidak aktif 2 hari+', 'Tidak ada aktivitas CRM tercatat. Check-in singkat biasanya memperbaikinya.'),
    (v_ver, 'ID', 'en', '⚠ {{participant_name}} has been inactive 2+ days', 'No CRM activity logged. A short check-in usually turns this around.')
  on conflict (version_id, country, locale) do nothing;

  -- appointment_reminder: Appointment or viewing is close
  insert into ch_notification_templates (code, purpose, audience, notify_type, variables, status)
  values ('appointment_reminder', 'Appointment or viewing is close', 'participant', 'challenge', array['lead_name','due_date']::text[], 'active')
  on conflict (code) do nothing;
  insert into ch_notification_template_versions (template_code, version, status, published_at)
  values ('appointment_reminder', 1, 'published', now())
  on conflict (template_code, version) do nothing
  returning id into v_ver;
  if v_ver is null then select id into v_ver from ch_notification_template_versions
    where template_code = 'appointment_reminder' and version = 1; end if;
  insert into ch_notification_template_translations (version_id, country, locale, title, body) values
    (v_ver, 'MY', 'ms-MY', '📅 Temujanji akan datang', '{{lead_name}} — {{due_date}}. Semak persediaan anda dalam Hero.'),
    (v_ver, 'MY', 'en', '📅 Upcoming appointment', '{{lead_name}} — {{due_date}}. Review your preparation in Hero.'),
    (v_ver, 'ID', 'id-ID', '📅 Janji temu mendatang', '{{lead_name}} — {{due_date}}. Tinjau persiapan Anda di Hero.'),
    (v_ver, 'ID', 'en', '📅 Upcoming appointment', '{{lead_name}} — {{due_date}}. Review your preparation in Hero.')
  on conflict (version_id, country, locale) do nothing;

  -- streak_at_risk: Consecutive-day run is about to break
  insert into ch_notification_templates (code, purpose, audience, notify_type, variables, status)
  values ('streak_at_risk', 'Consecutive-day run is about to break', 'participant', 'challenge', array['challenge_day']::text[], 'active')
  on conflict (code) do nothing;
  insert into ch_notification_template_versions (template_code, version, status, published_at)
  values ('streak_at_risk', 1, 'published', now())
  on conflict (template_code, version) do nothing
  returning id into v_ver;
  if v_ver is null then select id into v_ver from ch_notification_template_versions
    where template_code = 'streak_at_risk' and version = 1; end if;
  insert into ch_notification_template_translations (version_id, country, locale, title, body) values
    (v_ver, 'MY', 'ms-MY', '🔥 Rentetan anda dalam risiko', 'Hari {{challenge_day}} belum dihantar hari ini.'),
    (v_ver, 'MY', 'en', '🔥 Your streak is at risk', 'Day {{challenge_day}} has not been submitted today.'),
    (v_ver, 'ID', 'id-ID', '🔥 Streak Anda berisiko', 'Hari {{challenge_day}} belum dikirim hari ini.'),
    (v_ver, 'ID', 'en', '🔥 Your streak is at risk', 'Day {{challenge_day}} has not been submitted today.')
  on conflict (version_id, country, locale) do nothing;

  -- milestone_achieved: Milestone of verified days
  insert into ch_notification_templates (code, purpose, audience, notify_type, variables, status)
  values ('milestone_achieved', 'Milestone of verified days', 'participant', 'milestone', array['count','percent']::text[], 'active')
  on conflict (code) do nothing;
  insert into ch_notification_template_versions (template_code, version, status, published_at)
  values ('milestone_achieved', 1, 'published', now())
  on conflict (template_code, version) do nothing
  returning id into v_ver;
  if v_ver is null then select id into v_ver from ch_notification_template_versions
    where template_code = 'milestone_achieved' and version = 1; end if;
  insert into ch_notification_template_translations (version_id, country, locale, title, body) values
    (v_ver, 'MY', 'ms-MY', '🎯 Pencapaian: {{count}} hari disahkan', 'Anda {{percent}}% melalui cabaran ini.'),
    (v_ver, 'MY', 'en', '🎯 Milestone: {{count}} days verified', 'You are {{percent}}% through the challenge.'),
    (v_ver, 'ID', 'id-ID', '🎯 Pencapaian: {{count}} hari terverifikasi', 'Anda {{percent}}% melewati tantangan ini.'),
    (v_ver, 'ID', 'en', '🎯 Milestone: {{count}} days verified', 'You are {{percent}}% through the challenge.')
  on conflict (version_id, country, locale) do nothing;

  -- badge_earned: Badge awarded
  insert into ch_notification_templates (code, purpose, audience, notify_type, variables, status)
  values ('badge_earned', 'Badge awarded', 'participant', 'badge', array['badge_name','badge_icon']::text[], 'active')
  on conflict (code) do nothing;
  insert into ch_notification_template_versions (template_code, version, status, published_at)
  values ('badge_earned', 1, 'published', now())
  on conflict (template_code, version) do nothing
  returning id into v_ver;
  if v_ver is null then select id into v_ver from ch_notification_template_versions
    where template_code = 'badge_earned' and version = 1; end if;
  insert into ch_notification_template_translations (version_id, country, locale, title, body) values
    (v_ver, 'MY', 'ms-MY', '{{badge_icon}} Lencana diperoleh: {{badge_name}}', 'Konsisten itu berganda. Teruskan.'),
    (v_ver, 'MY', 'en', '{{badge_icon}} Badge earned: {{badge_name}}', 'Consistency compounds. Keep building.'),
    (v_ver, 'ID', 'id-ID', '{{badge_icon}} Lencana diraih: {{badge_name}}', 'Konsistensi itu berlipat. Terus bangun.'),
    (v_ver, 'ID', 'en', '{{badge_icon}} Badge earned: {{badge_name}}', 'Consistency compounds. Keep building.')
  on conflict (version_id, country, locale) do nothing;

  -- all_days_verified: All 30 days approved
  insert into ch_notification_templates (code, purpose, audience, notify_type, variables, status)
  values ('all_days_verified', 'All 30 days approved', 'participant', 'milestone', '{}'::text[], 'active')
  on conflict (code) do nothing;
  insert into ch_notification_template_versions (template_code, version, status, published_at)
  values ('all_days_verified', 1, 'published', now())
  on conflict (template_code, version) do nothing
  returning id into v_ver;
  if v_ver is null then select id into v_ver from ch_notification_template_versions
    where template_code = 'all_days_verified' and version = 1; end if;
  insert into ch_notification_template_translations (version_id, country, locale, title, body) values
    (v_ver, 'MY', 'ms-MY', '🏁 Semua 30 hari disahkan', 'Coach anda kini akan menyemak penyempurnaan program anda.'),
    (v_ver, 'MY', 'en', '🏁 All 30 days verified', 'Your Coach will now review your programme completion.'),
    (v_ver, 'ID', 'id-ID', '🏁 Semua 30 hari terverifikasi', 'Coach Anda kini akan meninjau penyelesaian program Anda.'),
    (v_ver, 'ID', 'en', '🏁 All 30 days verified', 'Your Coach will now review your programme completion.')
  on conflict (version_id, country, locale) do nothing;

  -- graduation_review_due: Human graduation review raised
  insert into ch_notification_templates (code, purpose, audience, notify_type, variables, status)
  values ('graduation_review_due', 'Human graduation review raised', 'coach', 'review', array['participant_name']::text[], 'active')
  on conflict (code) do nothing;
  insert into ch_notification_template_versions (template_code, version, status, published_at)
  values ('graduation_review_due', 1, 'published', now())
  on conflict (template_code, version) do nothing
  returning id into v_ver;
  if v_ver is null then select id into v_ver from ch_notification_template_versions
    where template_code = 'graduation_review_due' and version = 1; end if;
  insert into ch_notification_template_translations (version_id, country, locale, title, body) values
    (v_ver, 'MY', 'ms-MY', '🎓 Semakan graduasi diperlukan', '{{participant_name}} melengkapkan 30 hari yang disahkan. Graduasi ialah keputusan anda — tidak pernah automatik.'),
    (v_ver, 'MY', 'en', '🎓 Graduation review required', '{{participant_name}} completed 30 verified days. Graduation is your decision — never automatic.'),
    (v_ver, 'ID', 'id-ID', '🎓 Tinjauan kelulusan diperlukan', '{{participant_name}} menyelesaikan 30 hari terverifikasi. Kelulusan adalah keputusan Anda — tidak pernah otomatis.'),
    (v_ver, 'ID', 'en', '🎓 Graduation review required', '{{participant_name}} completed 30 verified days. Graduation is your decision — never automatic.')
  on conflict (version_id, country, locale) do nothing;

  -- day27_review_due: Day 27 structured review
  insert into ch_notification_templates (code, purpose, audience, notify_type, variables, status)
  values ('day27_review_due', 'Day 27 structured review', 'coach', 'review', array['participant_name']::text[], 'active')
  on conflict (code) do nothing;
  insert into ch_notification_template_versions (template_code, version, status, published_at)
  values ('day27_review_due', 1, 'published', now())
  on conflict (template_code, version) do nothing
  returning id into v_ver;
  if v_ver is null then select id into v_ver from ch_notification_template_versions
    where template_code = 'day27_review_due' and version = 1; end if;
  insert into ch_notification_template_translations (version_id, country, locale, title, body) values
    (v_ver, 'MY', 'ms-MY', '🧭 Hari 27 — semakan berstruktur untuk {{participant_name}}', 'Hero telah menjana ringkasan. Semak aktiviti, pipeline, halangan dan tindakan yang dipersetujui.'),
    (v_ver, 'MY', 'en', '🧭 Day 27 — structured review due for {{participant_name}}', 'Hero has generated the summary. Review activity, pipeline, bottleneck and agreed next actions.'),
    (v_ver, 'ID', 'id-ID', '🧭 Hari 27 — tinjauan terstruktur untuk {{participant_name}}', 'Hero telah membuat ringkasan. Tinjau aktivitas, pipeline, hambatan dan tindakan yang disepakati.'),
    (v_ver, 'ID', 'en', '🧭 Day 27 — structured review due for {{participant_name}}', 'Hero has generated the summary. Review activity, pipeline, bottleneck and agreed next actions.')
  on conflict (version_id, country, locale) do nothing;

  -- day30_review_due: Day 30 final review
  insert into ch_notification_templates (code, purpose, audience, notify_type, variables, status)
  values ('day30_review_due', 'Day 30 final review', 'coach', 'review', array['participant_name']::text[], 'active')
  on conflict (code) do nothing;
  insert into ch_notification_template_versions (template_code, version, status, published_at)
  values ('day30_review_due', 1, 'published', now())
  on conflict (template_code, version) do nothing
  returning id into v_ver;
  if v_ver is null then select id into v_ver from ch_notification_template_versions
    where template_code = 'day30_review_due' and version = 1; end if;
  insert into ch_notification_template_translations (version_id, country, locale, title, body) values
    (v_ver, 'MY', 'ms-MY', '🏁 Hari 30 — semakan akhir untuk {{participant_name}}', 'Penyempurnaan program, keupayaan, kemajuan pipeline dan langkah seterusnya. Graduasi kekal keputusan manusia.'),
    (v_ver, 'MY', 'en', '🏁 Day 30 — final review due for {{participant_name}}', 'Programme completion, capability, pipeline progress and next journey. Graduation stays a human decision.'),
    (v_ver, 'ID', 'id-ID', '🏁 Hari 30 — tinjauan akhir untuk {{participant_name}}', 'Penyelesaian program, kapabilitas, kemajuan pipeline dan langkah berikutnya. Kelulusan tetap keputusan manusia.'),
    (v_ver, 'ID', 'en', '🏁 Day 30 — final review due for {{participant_name}}', 'Programme completion, capability, pipeline progress and next journey. Graduation stays a human decision.')
  on conflict (version_id, country, locale) do nothing;

  -- day30_reached: Participant reached Day 30
  insert into ch_notification_templates (code, purpose, audience, notify_type, variables, status)
  values ('day30_reached', 'Participant reached Day 30', 'participant', 'milestone', '{}'::text[], 'active')
  on conflict (code) do nothing;
  insert into ch_notification_template_versions (template_code, version, status, published_at)
  values ('day30_reached', 1, 'published', now())
  on conflict (template_code, version) do nothing
  returning id into v_ver;
  if v_ver is null then select id into v_ver from ch_notification_template_versions
    where template_code = 'day30_reached' and version = 1; end if;
  insert into ch_notification_template_translations (version_id, country, locale, title, body) values
    (v_ver, 'MY', 'ms-MY', '🏁 Anda sampai Hari 30', 'Coach anda kini akan menjalankan semakan akhir anda.'),
    (v_ver, 'MY', 'en', '🏁 You have reached Day 30', 'Your Coach will now run your final review.'),
    (v_ver, 'ID', 'id-ID', '🏁 Anda mencapai Hari 30', 'Coach Anda kini akan menjalankan tinjauan akhir Anda.'),
    (v_ver, 'ID', 'en', '🏁 You have reached Day 30', 'Your Coach will now run your final review.')
  on conflict (version_id, country, locale) do nothing;

  -- closing_submitted: Closing sent for verification
  insert into ch_notification_templates (code, purpose, audience, notify_type, variables, status)
  values ('closing_submitted', 'Closing sent for verification', 'coach', 'review', array['participant_name','lead_name']::text[], 'active')
  on conflict (code) do nothing;
  insert into ch_notification_template_versions (template_code, version, status, published_at)
  values ('closing_submitted', 1, 'published', now())
  on conflict (template_code, version) do nothing
  returning id into v_ver;
  if v_ver is null then select id into v_ver from ch_notification_template_versions
    where template_code = 'closing_submitted' and version = 1; end if;
  insert into ch_notification_template_translations (version_id, country, locale, title, body) values
    (v_ver, 'MY', 'ms-MY', '🏁 Closing dihantar untuk pengesahan', 'Lead: {{lead_name}} — pengesahan manusia diperlukan.'),
    (v_ver, 'MY', 'en', '🏁 Closing submitted for verification', 'Lead: {{lead_name}} — human verification required.'),
    (v_ver, 'ID', 'id-ID', '🏁 Closing dikirim untuk verifikasi', 'Lead: {{lead_name}} — verifikasi manusia diperlukan.'),
    (v_ver, 'ID', 'en', '🏁 Closing submitted for verification', 'Lead: {{lead_name}} — human verification required.')
  on conflict (version_id, country, locale) do nothing;

  -- closing_verified: Closing verified by a human
  insert into ch_notification_templates (code, purpose, audience, notify_type, variables, status)
  values ('closing_verified', 'Closing verified by a human', 'participant', 'closing', array['xp_amount']::text[], 'active')
  on conflict (code) do nothing;
  insert into ch_notification_template_versions (template_code, version, status, published_at)
  values ('closing_verified', 1, 'published', now())
  on conflict (template_code, version) do nothing
  returning id into v_ver;
  if v_ver is null then select id into v_ver from ch_notification_template_versions
    where template_code = 'closing_verified' and version = 1; end if;
  insert into ch_notification_template_translations (version_id, country, locale, title, body) values
    (v_ver, 'MY', 'ms-MY', '🏆 Closing DISAHKAN', 'Closing anda disahkan oleh penyemak manusia. +{{xp_amount}} XP.'),
    (v_ver, 'MY', 'en', '🏆 Closing VERIFIED', 'Your closing was verified by a human reviewer. +{{xp_amount}} XP.'),
    (v_ver, 'ID', 'id-ID', '🏆 Closing TERVERIFIKASI', 'Closing Anda diverifikasi oleh peninjau manusia. +{{xp_amount}} XP.'),
    (v_ver, 'ID', 'en', '🏆 Closing VERIFIED', 'Your closing was verified by a human reviewer. +{{xp_amount}} XP.')
  on conflict (version_id, country, locale) do nothing;

  -- closing_needs_more: Closing sent back for documentation
  insert into ch_notification_templates (code, purpose, audience, notify_type, variables, status)
  values ('closing_needs_more', 'Closing sent back for documentation', 'participant', 'closing', array['review_note']::text[], 'active')
  on conflict (code) do nothing;
  insert into ch_notification_template_versions (template_code, version, status, published_at)
  values ('closing_needs_more', 1, 'published', now())
  on conflict (template_code, version) do nothing
  returning id into v_ver;
  if v_ver is null then select id into v_ver from ch_notification_template_versions
    where template_code = 'closing_needs_more' and version = 1; end if;
  insert into ch_notification_template_translations (version_id, country, locale, title, body) values
    (v_ver, 'MY', 'ms-MY', '🔄 Closing perlu tambahan', '{{review_note}}'),
    (v_ver, 'MY', 'en', '🔄 Closing needs more', '{{review_note}}'),
    (v_ver, 'ID', 'id-ID', '🔄 Closing perlu tambahan', '{{review_note}}'),
    (v_ver, 'ID', 'en', '🔄 Closing needs more', '{{review_note}}')
  on conflict (version_id, country, locale) do nothing;

  -- post_closing_available: Post-closing journey opened
  insert into ch_notification_templates (code, purpose, audience, notify_type, variables, status)
  values ('post_closing_available', 'Post-closing journey opened', 'participant', 'journey', '{}'::text[], 'active')
  on conflict (code) do nothing;
  insert into ch_notification_template_versions (template_code, version, status, published_at)
  values ('post_closing_available', 1, 'published', now())
  on conflict (template_code, version) do nothing
  returning id into v_ver;
  if v_ver is null then select id into v_ver from ch_notification_template_versions
    where template_code = 'post_closing_available' and version = 1; end if;
  insert into ch_notification_template_translations (version_id, country, locale, title, body) values
    (v_ver, 'MY', 'ms-MY', '🎓 Perjalanan Pasca-Closing tersedia', 'Refleksi, khidmat, rekrut dan mengajar — laluan Elite Coach anda bermula di sini.'),
    (v_ver, 'MY', 'en', '🎓 Post-Closing Journey available', 'Reflection, service, recruit and teach — your Elite Coach path starts here.'),
    (v_ver, 'ID', 'id-ID', '🎓 Perjalanan Pasca-Closing tersedia', 'Refleksi, layanan, rekrut dan mengajar — jalur Elite Coach Anda dimulai di sini.'),
    (v_ver, 'ID', 'en', '🎓 Post-Closing Journey available', 'Reflection, service, recruit and teach — your Elite Coach path starts here.')
  on conflict (version_id, country, locale) do nothing;

  -- coach_assigned_coach: Coach told a warrior was assigned
  insert into ch_notification_templates (code, purpose, audience, notify_type, variables, status)
  values ('coach_assigned_coach', 'Coach told a warrior was assigned', 'coach', 'coaching', array['participant_name']::text[], 'active')
  on conflict (code) do nothing;
  insert into ch_notification_template_versions (template_code, version, status, published_at)
  values ('coach_assigned_coach', 1, 'published', now())
  on conflict (template_code, version) do nothing
  returning id into v_ver;
  if v_ver is null then select id into v_ver from ch_notification_template_versions
    where template_code = 'coach_assigned_coach' and version = 1; end if;
  insert into ch_notification_template_translations (version_id, country, locale, title, body) values
    (v_ver, 'MY', 'ms-MY', '👥 Warrior baharu ditugaskan', 'Anda kini Coach untuk {{participant_name}}. Semakan mereka datang kepada anda.'),
    (v_ver, 'MY', 'en', '👥 New warrior assigned', 'You are now the Coach for {{participant_name}}. Their reviews come to you.'),
    (v_ver, 'ID', 'id-ID', '👥 Warrior baru ditugaskan', 'Anda kini Coach untuk {{participant_name}}. Tinjauan mereka datang ke Anda.'),
    (v_ver, 'ID', 'en', '👥 New warrior assigned', 'You are now the Coach for {{participant_name}}. Their reviews come to you.')
  on conflict (version_id, country, locale) do nothing;

  -- coach_assigned_participant: Warrior told who their coach is
  insert into ch_notification_templates (code, purpose, audience, notify_type, variables, status)
  values ('coach_assigned_participant', 'Warrior told who their coach is', 'participant', 'coaching', array['coach_name']::text[], 'active')
  on conflict (code) do nothing;
  insert into ch_notification_template_versions (template_code, version, status, published_at)
  values ('coach_assigned_participant', 1, 'published', now())
  on conflict (template_code, version) do nothing
  returning id into v_ver;
  if v_ver is null then select id into v_ver from ch_notification_template_versions
    where template_code = 'coach_assigned_participant' and version = 1; end if;
  insert into ch_notification_template_translations (version_id, country, locale, title, body) values
    (v_ver, 'MY', 'ms-MY', '🧭 Coach anda', '{{coach_name}} kini Coach anda untuk Cabaran Closing 30 Hari.'),
    (v_ver, 'MY', 'en', '🧭 Your Coach', '{{coach_name}} is now your Coach for the 30 Days Closing Challenge.'),
    (v_ver, 'ID', 'id-ID', '🧭 Coach Anda', '{{coach_name}} kini Coach Anda untuk Tantangan Closing 30 Hari.'),
    (v_ver, 'ID', 'en', '🧭 Your Coach', '{{coach_name}} is now your Coach for the 30 Days Closing Challenge.')
  on conflict (version_id, country, locale) do nothing;

  -- xp_reversed: A verified XP award was reversed
  insert into ch_notification_templates (code, purpose, audience, notify_type, variables, status)
  values ('xp_reversed', 'A verified XP award was reversed', 'participant', 'xp', array['reason']::text[], 'active')
  on conflict (code) do nothing;
  insert into ch_notification_template_versions (template_code, version, status, published_at)
  values ('xp_reversed', 1, 'published', now())
  on conflict (template_code, version) do nothing
  returning id into v_ver;
  if v_ver is null then select id into v_ver from ch_notification_template_versions
    where template_code = 'xp_reversed' and version = 1; end if;
  insert into ch_notification_template_translations (version_id, country, locale, title, body) values
    (v_ver, 'MY', 'ms-MY', '↩️ XP diselaraskan', 'Satu anugerah XP telah dibalikkan oleh penyemak. Sebab: {{reason}}'),
    (v_ver, 'MY', 'en', '↩️ XP adjusted', 'An XP award was reversed by a reviewer. Reason: {{reason}}'),
    (v_ver, 'ID', 'id-ID', '↩️ XP disesuaikan', 'Satu pemberian XP dibalik oleh peninjau. Alasan: {{reason}}'),
    (v_ver, 'ID', 'en', '↩️ XP adjusted', 'An XP award was reversed by a reviewer. Reason: {{reason}}')
  on conflict (version_id, country, locale) do nothing;

  -- enrolment_status: Enrolment paused / resumed / withdrawn
  insert into ch_notification_templates (code, purpose, audience, notify_type, variables, status)
  values ('enrolment_status', 'Enrolment paused / resumed / withdrawn', 'participant', 'challenge', array['review_status','reason']::text[], 'active')
  on conflict (code) do nothing;
  insert into ch_notification_template_versions (template_code, version, status, published_at)
  values ('enrolment_status', 1, 'published', now())
  on conflict (template_code, version) do nothing
  returning id into v_ver;
  if v_ver is null then select id into v_ver from ch_notification_template_versions
    where template_code = 'enrolment_status' and version = 1; end if;
  insert into ch_notification_template_translations (version_id, country, locale, title, body) values
    (v_ver, 'MY', 'ms-MY', '📋 Status cabaran anda: {{review_status}}', '{{reason}}'),
    (v_ver, 'MY', 'en', '📋 Your challenge status: {{review_status}}', '{{reason}}'),
    (v_ver, 'ID', 'id-ID', '📋 Status tantangan Anda: {{review_status}}', '{{reason}}'),
    (v_ver, 'ID', 'en', '📋 Your challenge status: {{review_status}}', '{{reason}}')
  on conflict (version_id, country, locale) do nothing;

  -- day_marked: A day was marked missed or excused
  insert into ch_notification_templates (code, purpose, audience, notify_type, variables, status)
  values ('day_marked', 'A day was marked missed or excused', 'participant', 'challenge', array['challenge_day','review_status','reason']::text[], 'active')
  on conflict (code) do nothing;
  insert into ch_notification_template_versions (template_code, version, status, published_at)
  values ('day_marked', 1, 'published', now())
  on conflict (template_code, version) do nothing
  returning id into v_ver;
  if v_ver is null then select id into v_ver from ch_notification_template_versions
    where template_code = 'day_marked' and version = 1; end if;
  insert into ch_notification_template_translations (version_id, country, locale, title, body) values
    (v_ver, 'MY', 'ms-MY', '📌 Hari {{challenge_day}}: {{review_status}}', '{{reason}}'),
    (v_ver, 'MY', 'en', '📌 Day {{challenge_day}}: {{review_status}}', '{{reason}}'),
    (v_ver, 'ID', 'id-ID', '📌 Hari {{challenge_day}}: {{review_status}}', '{{reason}}'),
    (v_ver, 'ID', 'en', '📌 Day {{challenge_day}}: {{review_status}}', '{{reason}}')
  on conflict (version_id, country, locale) do nothing;

  raise notice 'seeded 38 notification templates';
end $seed$;

